# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
__all__ = [
    "AnalyzeException",
    "BlockedByConcurrentOperationException",
    "BlockedByHighPriorityTransactionException",
    "CcException",
    "CheckConstraintViolationException",
    "CompileException",
    "ConflictOnWritePreserveException",
    "ConstraintViolationException",
    "DataCorruptionException",
    "DataError",
    "DatabaseError",
    "DependenciesViolationException",
    "DumpDirectoryInaccessibleException",
    "DumpFileException",
    "Error",
    "EvaluationException",
    "InactiveTransactionException",
    "InconsistentStatementException",
    "IntegrityError",
    "InterfaceError",
    "InternalError",
    "InternalException",
    "InvalidDecimalValueException",
    "InvalidRuntimeValueException",
    "LoadFileException",
    "LoadFileFormatException",
    "LoadFileNotFoundException",
    "LtxException",
    "LtxReadException",
    "LtxWriteException",
    "LtxWriteOperationWithoutWritePreserveException",
    "NotNullConstraintViolationException",
    "NotSupportedError",
    "OccException",
    "OccReadException",
    "OccWriteException",
    "OperationalError",
    "ParameterException",
    "ProgrammingError",
    "ReadOperationOnRestrictedReadAreaException",
    "ReferentialIntegrityConstraintViolationException",
    "RequestFailureException",
    "RestrictedOperationException",
    "RtxException",
    "ScalarSubqueryEvaluationException",
    "SecondaryIndexCorruptionException",
    "ServerException",
    "SqlExecutionException",
    "SqlLimitReachedException",
    "SqlRequestTimeoutException",
    "SqlServiceException",
    "StatementNotFoundException",
    "SymbolAnalyzeException",
    "SyntaxException",
    "TargetAlreadyExistsException",
    "TargetNotFoundException",
    "TransactionExceededLimitException",
    "TransactionNotFoundException",
    "TypeAnalyzeException",
    "UniqueConstraintViolationException",
    "UnresolvedPlaceholderException",
    "UnsupportedCompilerFeatureException",
    "UnsupportedRuntimeFeatureException",
    "ValueAnalyzeException",
    "ValueEvaluationException",
    "ValueOutOfRangeException",
    "ValueTooLongException",
    "Warning",
    "WriteOperationByRtxException",
]

class AnalyzeException(CompileException):
    r"""
    Tsurugi AnalyzeException
    """
    ...

class BlockedByConcurrentOperationException(CcException):
    r"""
    Tsurugi BlockedByConcurrentOperationException
    """
    ...

class BlockedByHighPriorityTransactionException(SqlExecutionException):
    r"""
    Tsurugi BlockedByHighPriorityTransactionException
    """
    ...

class CcException(SqlServiceException):
    r"""
    Tsurugi CcException
    """
    ...

class CheckConstraintViolationException(ConstraintViolationException):
    r"""
    Tsurugi CheckConstraintViolationException
    """
    ...

class CompileException(ProgrammingError):
    r"""
    Tsurugi CompileException
    """
    ...

class ConflictOnWritePreserveException(OccReadException):
    r"""
    Tsurugi ConflictOnWritePreserveException
    """
    ...

class ConstraintViolationException(IntegrityError):
    r"""
    Tsurugi ConstraintViolationException
    """
    ...

class DataCorruptionException(SqlExecutionException):
    r"""
    Tsurugi DataCorruptionException
    """
    ...

class DataError(DatabaseError):
    r"""
    data error (PEP 249)
    """
    ...

class DatabaseError(Error):
    r"""
    database error (PEP 249)
    """
    ...

class DependenciesViolationException(RestrictedOperationException):
    r"""
    Tsurugi DependenciesViolationException
    """
    ...

class DumpDirectoryInaccessibleException(DumpFileException):
    r"""
    Tsurugi DumpDirectoryInaccessibleException
    """
    ...

class DumpFileException(SqlExecutionException):
    r"""
    Tsurugi DumpFileException
    """
    ...

class Error(builtins.Exception):
    r"""
    base class of all other exceptions (PEP 249)
    """
    ...

class EvaluationException(DataError):
    r"""
    Tsurugi EvaluationException
    """
    ...

class InactiveTransactionException(RestrictedOperationException):
    r"""
    Tsurugi InactiveTransactionException
    """
    ...

class InconsistentStatementException(SqlExecutionException):
    r"""
    Tsurugi InconsistentStatementException
    """
    ...

class IntegrityError(DatabaseError):
    r"""
    integrity error (PEP 249)
    """
    ...

class InterfaceError(Error):
    r"""
    interface error (PEP 249)
    """
    ...

class InternalError(DatabaseError):
    r"""
    internal error (PEP 249)
    """
    ...

class InternalException(InternalError):
    r"""
    Tsurugi InternalException
    """
    ...

class InvalidDecimalValueException(InvalidRuntimeValueException):
    r"""
    Tsurugi InvalidDecimalValueException
    """
    ...

class InvalidRuntimeValueException(SqlLimitReachedException):
    r"""
    Tsurugi InvalidRuntimeValueException
    """
    ...

class LoadFileException(SqlExecutionException):
    r"""
    Tsurugi LoadFileException
    """
    ...

class LoadFileFormatException(LoadFileException):
    r"""
    Tsurugi LoadFileFormatException
    """
    ...

class LoadFileNotFoundException(LoadFileException):
    r"""
    Tsurugi LoadFileNotFoundException
    """
    ...

class LtxException(CcException):
    r"""
    Tsurugi LtxException
    """
    ...

class LtxReadException(LtxException):
    r"""
    Tsurugi LtxReadException
    """
    ...

class LtxWriteException(LtxException):
    r"""
    Tsurugi LtxWriteException
    """
    ...

class LtxWriteOperationWithoutWritePreserveException(RestrictedOperationException):
    r"""
    Tsurugi LtxWriteOperationWithoutWritePreserveException
    """
    ...

class NotNullConstraintViolationException(ConstraintViolationException):
    r"""
    Tsurugi NotNullConstraintViolationException
    """
    ...

class NotSupportedError(DatabaseError):
    r"""
    not supported error (PEP 249)
    """
    ...

class OccException(CcException):
    r"""
    Tsurugi OccException
    """
    ...

class OccReadException(OccException):
    r"""
    Tsurugi OccReadException
    """
    ...

class OccWriteException(OccException):
    r"""
    Tsurugi OccWriteException
    """
    ...

class OperationalError(DatabaseError):
    r"""
    operation error (PEP 249)
    """
    ...

class ParameterException(ProgrammingError):
    r"""
    Tsurugi ParameterException
    """
    ...

class ProgrammingError(DatabaseError):
    r"""
    programming error (PEP 249)
    """
    ...

class ReadOperationOnRestrictedReadAreaException(RestrictedOperationException):
    r"""
    Tsurugi ReadOperationOnRestrictedReadAreaException
    """
    ...

class ReferentialIntegrityConstraintViolationException(ConstraintViolationException):
    r"""
    Tsurugi ReferentialIntegrityConstraintViolationException
    """
    ...

class RequestFailureException(SqlExecutionException):
    r"""
    Tsurugi RequestFailureException
    """
    ...

class RestrictedOperationException(SqlExecutionException):
    r"""
    Tsurugi RestrictedOperationException
    """
    ...

class RtxException(CcException):
    r"""
    Tsurugi RtxException
    """
    ...

class ScalarSubqueryEvaluationException(EvaluationException):
    r"""
    Tsurugi ScalarSubqueryEvaluationException
    """
    ...

class SecondaryIndexCorruptionException(DataCorruptionException):
    r"""
    Tsurugi SecondaryIndexCorruptionException
    """
    ...

class ServerException(OperationalError):
    r"""
    Tsurugi ServerException
    """
    ...

class SqlExecutionException(SqlServiceException):
    r"""
    Tsurugi SqlExecutionException
    """
    ...

class SqlLimitReachedException(DataError):
    r"""
    Tsurugi SqlLimitReachedException
    """
    ...

class SqlRequestTimeoutException(SqlExecutionException):
    r"""
    Tsurugi SqlRequestTimeoutException
    """
    ...

class SqlServiceException(ServerException):
    r"""
    Tsurugi SqlServiceException
    """
    ...

class StatementNotFoundException(RequestFailureException):
    r"""
    Tsurugi StatementNotFoundException
    """
    ...

class SymbolAnalyzeException(AnalyzeException):
    r"""
    Tsurugi SymbolAnalyzeException
    """
    ...

class SyntaxException(CompileException):
    r"""
    Tsurugi SyntaxException
    """
    ...

class TargetAlreadyExistsException(SqlExecutionException):
    r"""
    Tsurugi TargetAlreadyExistsException
    """
    ...

class TargetNotFoundException(SqlExecutionException):
    r"""
    Tsurugi TargetNotFoundException
    """
    ...

class TransactionExceededLimitException(SqlLimitReachedException):
    r"""
    Tsurugi TransactionExceededLimitException
    """
    ...

class TransactionNotFoundException(RequestFailureException):
    r"""
    Tsurugi TransactionNotFoundException
    """
    ...

class TypeAnalyzeException(AnalyzeException):
    r"""
    Tsurugi TypeAnalyzeException
    """
    ...

class UniqueConstraintViolationException(ConstraintViolationException):
    r"""
    Tsurugi UniqueConstraintViolationException
    """
    ...

class UnresolvedPlaceholderException(ParameterException):
    r"""
    Tsurugi UnresolvedPlaceholderException
    """
    ...

class UnsupportedCompilerFeatureException(NotSupportedError):
    r"""
    Tsurugi UnsupportedCompilerFeatureException
    """
    ...

class UnsupportedRuntimeFeatureException(NotSupportedError):
    r"""
    Tsurugi UnsupportedRuntimeFeatureException
    """
    ...

class ValueAnalyzeException(AnalyzeException):
    r"""
    Tsurugi ValueAnalyzeException
    """
    ...

class ValueEvaluationException(EvaluationException):
    r"""
    Tsurugi ValueEvaluationException
    """
    ...

class ValueOutOfRangeException(InvalidRuntimeValueException):
    r"""
    Tsurugi ValueOutOfRangeException
    """
    ...

class ValueTooLongException(InvalidRuntimeValueException):
    r"""
    Tsurugi ValueTooLongException
    """
    ...

class Warning(builtins.Exception):
    r"""
    important warning (PEP 249)
    """
    ...

class WriteOperationByRtxException(RestrictedOperationException):
    r"""
    Tsurugi WriteOperationByRtxException
    """
    ...

