[package]
name = "tsubakuro-rust-client"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
log = "0.4.22"
prost = "0.13.3"
tokio = { version = "1.42.0", features = ["full"] }
url = "2.5.4"

[build-dependencies]
prost-build = "0.13.3"
