# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
from . import error
from . import type_code
__all__ = [
    "Column",
    "CommitOption",
    "CommitType",
    "Config",
    "Connection",
    "Cursor",
    "DataError",
    "DatabaseError",
    "Error",
    "IntegrityError",
    "InterfaceError",
    "InternalError",
    "NotSupportedError",
    "OperationalError",
    "ProgrammingError",
    "ShutdownOption",
    "ShutdownType",
    "TableMetadata",
    "TransactionOption",
    "TransactionType",
    "Warning",
    "connect",
    "env_logger_init",
    "error",
    "logging_init",
    "type_code",
]

@typing.final
class Column:
    r"""
    Column metadata.
    
    Attributes:
        name (str): Column name. (read only)
        description (Optional[str]): Column description. (read only)
        type_code (str): Type code. (read only)
        atom_type_code (int): AtomType code. -1 if unknown. (read only)
        sql_type (str): SQL type. (read only)
        sql_type_name (Optional[str]): SQL type name. (read only)
        length (Optional[int]): Length for string types. (read only)
        precision (Optional[int]): Precision for numeric types. (read only)
        scale (Optional[int]): Scale for numeric types. (read only)
        nullable (Optional[bool]): Nullable flag. (read only)
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Column name.
        """
    @property
    def description(self) -> typing.Optional[builtins.str]:
        r"""
        Column description.
        """
    @property
    def type_code(self) -> builtins.str:
        r"""
        type_code.
        """
    @property
    def atom_type_code(self) -> builtins.int:
        r"""
        AtomType code.
        """
    @property
    def sql_type(self) -> builtins.str:
        r"""
        SQL type.
        """
    @property
    def sql_type_name(self) -> typing.Optional[builtins.str]:
        r"""
        SQL type name.
        """
    @property
    def length(self) -> typing.Optional[builtins.int]:
        r"""
        Length.
        """
    @property
    def precision(self) -> typing.Optional[builtins.int]:
        r"""
        Precision.
        """
    @property
    def scale(self) -> typing.Optional[builtins.int]:
        r"""
        Scale.
        """
    @property
    def nullable(self) -> typing.Optional[builtins.bool]:
        r"""
        Nullable.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CommitOption:
    r"""
    Commit option for transaction.
    
    Attributes:
        commit_type (CommitType): Commit type. Default is `CommitType.DEFAULT`.
        auto_dispose (bool): Auto dispose flag. Default is `False`.
        commit_timeout (int): Commit timeout in seconds.
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
    
        commit_option = tsurugi.CommitOption(tsurugi.CommitType.DEFAULT, False, 60)
        ```
    """
    @property
    def commit_type(self) -> CommitType:
        r"""
        Commit type.
        """
    @commit_type.setter
    def commit_type(self, value: CommitType) -> None:
        r"""
        Commit type.
        """
    @property
    def auto_dispose(self) -> builtins.bool:
        r"""
        Auto dispose flag.
        """
    @auto_dispose.setter
    def auto_dispose(self, value: builtins.bool) -> None:
        r"""
        Auto dispose flag.
        """
    @property
    def commit_timeout(self) -> typing.Optional[builtins.int]:
        r"""
        Commit timeout in seconds.
        """
    @commit_timeout.setter
    def commit_timeout(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Commit timeout in seconds.
        """
    def __new__(cls, commit_type: CommitType = CommitType.DEFAULT, auto_dispose: builtins.bool = False, timeout: typing.Optional[builtins.int] = None) -> CommitOption:
        r"""
        Create a new `CommitOption`.
        
        Args:
            commit_type (CommitType): Commit type. Default is `CommitType.DEFAULT`.
            auto_dispose (bool, optional): Auto dispose flag. Default is `False`.
            timeout (int, optional): Commit timeout in seconds.
        
        Returns:
            CommitOption: A new `CommitOption` instance.
        """

@typing.final
class Config:
    r"""
    Configuration options for connecting to Tsurugi.
    
    Attributes:
        application_name (str): Application name.
        endpoint (str): Endpoint URL of the Tsurugi server.
        user (str): Username for authentication.
        password (str): Password for authentication.
        auth_token (str): Authentication token.
        credentials (str): Path to credentials file.
        session_label (str): Session label for the connection.
        transaction_option (TransactionOption): Transaction option.
        commit_option (CommitOption): Commit option.
        shutdown_option (ShutdownOption): Shutdown option.
        default_timeout (int): Default timeout in seconds.
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
    
        config = tsurugi.Config()
        config.application_name = "tsurugi-dbapi example"
        config.endpoint = "tcp://localhost:12345"
        config.user = "tsurugi"
        config.password = "password"
        config.session_label = "tsurugi-dbapi session"
        config.default_timeout = 30  # seconds
        ```
    
        ```python
        import tsurugi_dbapi as tsurugi
    
        config = tsurugi.Config(
            application_name="tsurugi-dbapi example",
            endpoint="tcp://localhost:12345",
            user="tsurugi",
            password="password",
            session_label="tsurugi-dbapi session",
            default_timeout=30,  # seconds
        )
        ```
    """
    @property
    def application_name(self) -> typing.Optional[builtins.str]:
        r"""
        Application name.
        """
    @application_name.setter
    def application_name(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Application name.
        """
    @property
    def endpoint(self) -> typing.Optional[builtins.str]:
        r"""
        Endpoint URL of the Tsurugi server.
        """
    @endpoint.setter
    def endpoint(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Endpoint URL of the Tsurugi server.
        """
    @property
    def user(self) -> typing.Optional[builtins.str]:
        r"""
        Username for authentication.
        """
    @user.setter
    def user(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Username for authentication.
        """
    @property
    def password(self) -> typing.Optional[builtins.str]:
        r"""
        Password for authentication.
        """
    @password.setter
    def password(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Password for authentication.
        """
    @property
    def auth_token(self) -> typing.Optional[builtins.str]:
        r"""
        Authentication token.
        """
    @auth_token.setter
    def auth_token(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Authentication token.
        """
    @property
    def credentials(self) -> typing.Optional[builtins.str]:
        r"""
        Path to credentials file.
        """
    @credentials.setter
    def credentials(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Path to credentials file.
        """
    @property
    def session_label(self) -> typing.Optional[builtins.str]:
        r"""
        Session label for the connection.
        """
    @session_label.setter
    def session_label(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Session label for the connection.
        """
    @property
    def transaction_option(self) -> typing.Optional[TransactionOption]:
        r"""
        Transaction option.
        """
    @transaction_option.setter
    def transaction_option(self, value: typing.Optional[TransactionOption]) -> None:
        r"""
        Transaction option.
        """
    @property
    def commit_option(self) -> typing.Optional[CommitOption]:
        r"""
        Commit option.
        """
    @commit_option.setter
    def commit_option(self, value: typing.Optional[CommitOption]) -> None:
        r"""
        Commit option.
        """
    @property
    def shutdown_option(self) -> typing.Optional[ShutdownOption]:
        r"""
        Shutdown option.
        """
    @shutdown_option.setter
    def shutdown_option(self, value: typing.Optional[ShutdownOption]) -> None:
        r"""
        Shutdown option.
        """
    @property
    def default_timeout(self) -> typing.Optional[builtins.int]:
        r"""
        Default timeout in seconds.
        """
    @default_timeout.setter
    def default_timeout(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Default timeout in seconds.
        """
    def __new__(cls, *args: typing.Any, **kwargs: typing.Any) -> Config:
        r"""
        Create a new `Config`.
        
        Args:
            *args (Config | TransactionOption | CommitOption | ShutdownOption | str, optional): other configuration object.
            **kwargs (dict, optional): e.g. `endpoint="tcp://localhost:12345"`, `user="tsurugi"`
        
        Returns:
            Config: configuration object.
        """
    def set(self, *args: typing.Any, **kwargs: typing.Any) -> None:
        r"""
        Set configuration options.
        
        Args:
            *args (Config | TransactionOption | CommitOption | ShutdownOption | str, optional): other configuration object.
            **kwargs (dict, optional): e.g. `endpoint="tcp://localhost:12345"`, `user="tsurugi"`
        """
    def merge(self, other: Config) -> None:
        r"""
        Merge another `Config` into this one.
        
        Args:
            other (Config): other configuration object.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Connection:
    r"""
    Connection to Tsurugi.
    
    Attributes:
        transaction_option (TransactionOption): Transaction option. (write only)
        commit_option (CommitOption): Commit option. (write only)
        shutdown_option (ShutdownOption): Shutdown option. (write only)
        closed (bool): Whether the connection is closed. (read only)
    """
    @property
    def closed(self) -> builtins.bool:
        r"""
        Whether the connection is closed.
        """
    @transaction_option.setter
    def transaction_option(self, value: TransactionOption) -> None:
        r"""
        Transaction option.
        """
    @commit_option.setter
    def commit_option(self, value: CommitOption) -> None:
        r"""
        Commit option.
        """
    @shutdown_option.setter
    def shutdown_option(self, value: ShutdownOption) -> None:
        r"""
        Shutdown option.
        """
    def list_tables(self) -> builtins.list[builtins.str]:
        r"""
        List table names.
        
        Returns:
            List[str]: List of table names.
        
        Examples:
            ```python
            table_names = connection.list_tables()
            ```
        """
    def get_table_metadata(self, table_name: builtins.str) -> TableMetadata:
        r"""
        Get table metadata.
        
        Args:
            table_name (str): Table name.
        
        Returns:
           TableMetadata: Table metadata.
        
        Raises:
            TargetNotFoundException: If the table does not exist.
        
        Examples:
            ```python
            import tsurugi_dbapi as tsurugi
        
            try:
                metadata = connection.get_table_metadata("my_table")
            except tsurugi.error.TargetNotFoundException:
                pass
            ```
        """
    def find_table_metadata(self, table_name: builtins.str) -> typing.Optional[TableMetadata]:
        r"""
        Find table metadata.
        
        Args:
            table_name (str): Table name.
        
        Returns:
            Optional[TableMetadata]: Table metadata, or None if the table does not exist.
        
        Examples:
            ```python
            metadata = connection.find_table_metadata("my_table")
            ```
        """
    def cursor(self, py_self: Connection) -> Cursor:
        r"""
        Create a new cursor object using the connection.
        
        Returns:
            Cursor: Cursor object.
        
        Examples:
            ```python
            with connection.cursor() as cursor:
               pass
            ```
        """
    def commit(self, option: typing.Optional[CommitOption] = None) -> None:
        r"""
        Commit the current transaction.
        
        Args:
            option (CommitOption, optional): CommitOption object.
        
        Examples:
            ```python
            connection.commit()
            ```
        """
    def rollback(self) -> None:
        r"""
        Rollback the current transaction.
        
        Examples:
            ```python
            connection.rollback()
            ```
        """
    def __enter__(self, slf: Connection) -> Connection:
        r"""
        Enter the runtime context related to this object.
        """
    def __exit__(self, _exc_type: typing.Optional[typing.Any], exc_value: typing.Optional[typing.Any], _traceback: typing.Optional[typing.Any]) -> None:
        r"""
        Exit the runtime context related to this object.
        """
    def close(self) -> None:
        r"""
        Close the connection.
        """

@typing.final
class Cursor:
    r"""
    Cursor object for executing SQL statements and fetching results.
    
    Attributes:
        connection (Connection): Connection object associated with the cursor. (read only)
        description (Optional[Sequence[Tuple[str, str, None, Optional[int], Optional[int], Optional[int], Optional[bool]]]]): Description of the query result set.
            `(name, type_code, display_size, internal_size, precision, scale, null_ok)`.  (read only)
        arraysize (int): Number of rows to fetch at a time with `Cursor.fetchmany()`. Default is 1.
        rownumber (int): Current row number (0-based). (read only)
        rowcount (int): Number of rows affected by the last `Cursor.execute*()` method. -1 if not applicable. (read only)
        closed (bool): Whether the cursor is closed. (read only)
    """
    @property
    def executemany_async(self) -> builtins.bool:
        r"""
        Whether to execute `Cursor.executemany()` asynchronously. Default is `True`.
        """
    @executemany_async.setter
    def executemany_async(self, value: builtins.bool) -> None:
        r"""
        Whether to execute `Cursor.executemany()` asynchronously. Default is `True`.
        """
    @property
    def arraysize(self) -> builtins.int:
        r"""
        Number of rows to fetch at a time with `Cursor.fetchmany()`.
        """
    @arraysize.setter
    def arraysize(self, value: builtins.int) -> None:
        r"""
        Number of rows to fetch at a time with `Cursor.fetchmany()`.
        """
    @property
    def rowcount(self) -> builtins.int:
        r"""
        Number of rows affected by the last `Cursor.execute*()` method.
        """
    @property
    def closed(self) -> builtins.bool:
        r"""
        Whether the cursor is closed.
        """
    @property
    def connection(self) -> Connection:
        r"""
        Connection object associated with the cursor. (read only)
        """
    @property
    def description(self) -> Optional[Sequence[Tuple[
        str,           # name
        str,           # type_code
        None,          # display_size
        Optional[int], # internal_size
        Optional[int], # precision
        Optional[int], # scale
        Optional[bool] # null_ok
    ]]]:
        r"""
        Description of the query result set.
        """
    @property
    def rownumber(self) -> typing.Optional[builtins.int]:
        r"""
        Current row number (0-based).
        """
    def execute(self, operation: builtins.str, parameters: typing.Optional[typing.Any] = None) -> None:
        r"""
        Execute a SQL statement.
        
        Args:
            operation (str): SQL statement to be executed.
            parameters (Tuple[Any, ...] | dict[str, Any], optional): Parameters for the SQL statement.
        
        Examples:
            ```python
            cursor.execute("insert into example values (1, 'Hello')")
            connection.commit()
            ```
        
            ```python
            cursor.execute("insert into example values (?, ?)", (1, "Hello"))
            connection.commit()
            ```
        
            ```python
            cursor.execute("insert into example values (:id, :name)", {"id": 1, "name": "Hello"})
            connection.commit()
            ```
        """
    def prepare(self, operation: builtins.str, parameters: typing.Any) -> None:
        r"""
        Prepare a SQL statement for execution.
        
        Args:
            operation (str): SQL statement to be prepared.
            parameters (Tuple[Any, ...] | dict[str, Any]): Parameters for the SQL statement.
        
        Examples:
            ```python
            import tsurugi_dbapi as tsurugi
        
            sql = "insert into example values (?, ?)"
            cursor.prepare(sql, (tsurugi.type_code.Int64, tsurugi.type_code.Str))
            cursor.execute(sql, (1, "Hello"))
            connection.commit()
            ```
        
            ```python
            import tsurugi_dbapi as tsurugi
        
            sql = "insert into example values (:id, :name)"
            cursor.prepare(sql, {"id": tsurugi.type_code.Int64, "name": tsurugi.type_code.Str})
            cursor.execute(sql, {"id": 1, "name": "Hello"})
            connection.commit()
            ```
        """
    def executemany(self, operation: builtins.str, seq_of_parameters: typing.Any) -> None:
        r"""
        Execute a prepared SQL statement multiple times.
        
        Args:
            operation (str): SQL statement to be executed.
            seq_of_parameters (Sequence[Tuple[Any, ...] | dict[str, Any]]): Sequence of parameters for the SQL statement.
        
        Examples:
            ```python
            cursor.executemany("insert into example values (?, ?)", [(1, "Hello"), (2, "World")])
            connection.commit()
            ```
        
            ```python
            cursor.executemany("insert into example values (:id, :name)", [{"id": 1, "name": "Hello"}, {"id": 2, "name": "World"}])
            connection.commit()
            ```
        """
    def fetchone(self) -> typing.Optional[tuple]:
        r"""
        Fetch the next row of a query result set.
        
        Returns:
              Optional[Tuple[Any, ...]]: A single sequence representing the next row of the result set, or `None` if no more data is available.
        
        Examples:
            ```python
            cursor.execute("select * from example where id = 1")
            row = cursor.fetchone()
            connection.commit()
            ```
        """
    def next(self) -> tuple:
        r"""
        Fetch the next row of a query result set.
        
        Returns:
             Tuple[Any, ...]: A single sequence representing the next row of the result set.
        
        Raises:
            StopIteration: When no more data is available.
        """
    def fetchmany(self, size: typing.Optional[builtins.int] = None) -> builtins.list[tuple]:
        r"""
        Fetch the next set of rows of a query result set.
        
        Args:
            size (int, optional) - Number of rows to fetch. If not specified, use the cursor's `arraysize` attribute.
        
        Returns:
             List[Tuple[Any, ...]]: A list of sequences, each representing a row of the result set.
        
        Examples:
            ```python
            cursor.execute("select * from example")
            rows = cursor.fetchmany(10)
            connection.commit()
            ```
        
        Note:
            See also `Cursor.arraysize` for setting the default number of rows to fetch with `fetchmany()`.
        """
    def fetchall(self) -> builtins.list[tuple]:
        r"""
        Fetch all (remaining) rows of a query result set.
        
        Returns:
             List[Tuple[Any, ...]]: A list of sequences, each representing a row of the result set.
        
        Examples:
            ```python
            cursor.execute("select * from example")
            rows = cursor.fetchall()
            connection.commit()
            ```
        """
    def callproc(self, _procname: builtins.str, _parameters: typing.Optional[typing.Any] = None) -> None:
        r"""
        Not supported in this implementation.
        """
    def nextset(self) -> None:
        r"""
        Not supported in this implementation.
        """
    def setinputsizes(self, _sizes: typing.Any) -> None:
        r"""
        This method is a no-op in this implementation.
        """
    def setoutputsize(self, _size: builtins.int, _column: typing.Optional[builtins.int] = None) -> None:
        r"""
        This method is a no-op in this implementation.
        """
    def __iter__(self, slf: Cursor) -> Cursor:
        r"""
        Iterator protocol: return the iterator object itself.
        """
    def __next__(self) -> tuple:
        r"""
        Iterator protocol: return the next row in the result set.
        """
    def __enter__(self, slf: Cursor) -> Cursor:
        r"""
        Enter the runtime context related to this object.
        """
    def __exit__(self, _exc_type: typing.Optional[typing.Any], exc_value: typing.Optional[typing.Any], _traceback: typing.Optional[typing.Any]) -> None:
        r"""
        Exit the runtime context related to this object.
        """
    def clear(self) -> None:
        r"""
        Closes the current result set and clears cached prepared statements.
        """
    def close(self) -> None:
        r"""
        Close the cursor.
        """

class DataError(DatabaseError):
    r"""
    data error (PEP 249)
    """
    ...

class DatabaseError(Error):
    r"""
    database error (PEP 249)
    """
    ...

class Error(builtins.Exception):
    r"""
    base class of all other exceptions (PEP 249)
    """
    ...

class IntegrityError(DatabaseError):
    r"""
    integrity error (PEP 249)
    """
    ...

class InterfaceError(Error):
    r"""
    interface error (PEP 249)
    """
    ...

class InternalError(DatabaseError):
    r"""
    internal error (PEP 249)
    """
    ...

class NotSupportedError(DatabaseError):
    r"""
    not supported error (PEP 249)
    """
    ...

class OperationalError(DatabaseError):
    r"""
    operation error (PEP 249)
    """
    ...

class ProgrammingError(DatabaseError):
    r"""
    programming error (PEP 249)
    """
    ...

@typing.final
class ShutdownOption:
    r"""
    Shutdown option for connection.
    
    Attributes:
        shutdown_type (ShutdownType): Shutdown type. Default is `ShutdownType.GRACEFUL`.
        shutdown_timeout (int): Shutdown timeout in seconds.
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
    
        shutdown_option = tsurugi.ShutdownOption(tsurugi.ShutdownType.GRACEFUL, 30)
        ```
    """
    @property
    def shutdown_type(self) -> ShutdownType:
        r"""
        Shutdown type.
        """
    @shutdown_type.setter
    def shutdown_type(self, value: ShutdownType) -> None:
        r"""
        Shutdown type.
        """
    @property
    def shutdown_timeout(self) -> typing.Optional[builtins.int]:
        r"""
        Shutdown timeout in seconds.
        """
    @shutdown_timeout.setter
    def shutdown_timeout(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Shutdown timeout in seconds.
        """
    def __new__(cls, shutdown_type: ShutdownType = ShutdownType.GRACEFUL, timeout: typing.Optional[builtins.int] = None) -> ShutdownOption:
        r"""
        Create a new `ShutdownOption`.
        
        Args:
            shutdown_type (ShutdownType): Shutdown type. Default is `ShutdownType.GRACEFUL`.
            timeout (int, optional): Shutdown timeout in seconds.
        
        Returns:
            ShutdownOption: A new `ShutdownOption` instance.
        """

@typing.final
class TableMetadata:
    r"""
    Table metadata.
    
    Attributes:
        database_name (str): Database name. (read only)
        schema_name (str): Schema name. (read only)
        table_name (str): Table name. (read only)
        table_description (Optional[str]): Table description. (read only)
        columns (List[Column]): Columns metadata. (read only)
        description (Sequence[Tuple[str, str, None, Optional[int], Optional[int], Optional[int], Optional[bool]]]): Columns description.
          `(name, type_code, display_size, internal_size, precision, scale, null_ok)`. (read only)
        primary_keys (List[str]): Primary keys. (read only)
    """
    @property
    def database_name(self) -> builtins.str:
        r"""
        Database name.
        """
    @property
    def schema_name(self) -> builtins.str:
        r"""
        Schema name.
        """
    @property
    def table_name(self) -> builtins.str:
        r"""
        Table name.
        """
    @property
    def table_description(self) -> typing.Optional[builtins.str]:
        r"""
        Table description.
        """
    @property
    def columns(self) -> builtins.list[Column]:
        r"""
        Columns metadata.
        """
    @property
    def description(self) -> Sequence[Tuple[
        str,           # name
        str,           # type_code
        None,          # display_size
        Optional[int], # internal_size
        Optional[int], # precision
        Optional[int], # scale
        Optional[bool] # null_ok
    ]]:
        r"""
        Columns description.
        """
    @property
    def primary_keys(self) -> builtins.list[builtins.str]:
        r"""
        Primary keys.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class TransactionOption:
    r"""
    Transaction option.
    
    Attributes:
        transaction_type (TransactionType): Transaction type. Default is `TransactionType.OCC`.
        label (str): Transaction label.
        include_ddl (bool): Whether the transaction modifies definitions (DDL). Default is `False`. Only applicable for `TransactionType.LTX`.
        write_preserve (List[str]): List of table names to preserve for write operations. Only applicable for `TransactionType.LTX`.
        inclusive_read_area (List[str]): List of table names to include in the read area. Only applicable for `TransactionType.LTX`.
        exclusive_read_area (List[str]): List of table names to exclude from the read area. Only applicable for `TransactionType.LTX`.
        scan_parallel (int): Degree of parallelism for scanning. Only applicable for `TransactionType.RTX`.
        begin_timeout (int): Begin transaction timeout in seconds
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
    
        tx_option = tsurugi.TransactionOption(tsurugi.TransactionType.OCC)
        tx_option.label = "tsurugi-dbapi OCC example"
        ```
    
        ```python
        import tsurugi_dbapi as tsurugi
    
        tx_option = tsurugi.TransactionOption(tsurugi.TransactionType.LTX)
        tx_option.label = "tsurugi-dbapi LTX example"
        tx_option.write_preserve = ["table1", "table2"]
        ```
    
        ```python
        import tsurugi_dbapi as tsurugi
    
        tx_option = tsurugi.TransactionOption(tsurugi.TransactionType.RTX)
        tx_option.label = "tsurugi-dbapi RTX example"
        tx_option.scan_parallel = 4
        ```
    """
    @property
    def transaction_type(self) -> TransactionType:
        r"""
        Transaction type.
        """
    @transaction_type.setter
    def transaction_type(self, value: TransactionType) -> None:
        r"""
        Transaction type.
        """
    @property
    def label(self) -> typing.Optional[builtins.str]:
        r"""
        Transaction label.
        """
    @label.setter
    def label(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Transaction label.
        """
    @property
    def include_ddl(self) -> builtins.bool:
        r"""
        Include DDL flag.
        """
    @include_ddl.setter
    def include_ddl(self, value: builtins.bool) -> None:
        r"""
        Include DDL flag.
        """
    @property
    def write_preserve(self) -> typing.Optional[builtins.list[builtins.str]]:
        r"""
        Write preserve.
        """
    @write_preserve.setter
    def write_preserve(self, value: typing.Optional[builtins.list[builtins.str]]) -> None:
        r"""
        Write preserve.
        """
    @property
    def inclusive_read_area(self) -> typing.Optional[builtins.list[builtins.str]]:
        r"""
        Inclusive read area.
        """
    @inclusive_read_area.setter
    def inclusive_read_area(self, value: typing.Optional[builtins.list[builtins.str]]) -> None:
        r"""
        Inclusive read area.
        """
    @property
    def exclusive_read_area(self) -> typing.Optional[builtins.list[builtins.str]]:
        r"""
        Exclusive read area.
        """
    @exclusive_read_area.setter
    def exclusive_read_area(self, value: typing.Optional[builtins.list[builtins.str]]) -> None:
        r"""
        Exclusive read area.
        """
    @property
    def scan_parallel(self) -> typing.Optional[builtins.int]:
        r"""
        Scan parallel.
        """
    @scan_parallel.setter
    def scan_parallel(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Scan parallel.
        """
    @property
    def begin_timeout(self) -> typing.Optional[builtins.int]:
        r"""
        Begin transaction timeout in seconds.
        """
    @begin_timeout.setter
    def begin_timeout(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Begin transaction timeout in seconds.
        """
    def __new__(cls, r#type: TransactionType = TransactionType.OCC) -> TransactionOption:
        r"""
        Create a new `TransactionOption`.
        
        Args:
            type (TransactionType): Transaction type. Default is `TransactionType.OCC`.
        
        Returns:
            TransactionOption: A new `TransactionOption` instance.
        """
    @classmethod
    def occ(cls, label: typing.Optional[builtins.str] = None) -> TransactionOption:
        r"""
        Create a new `TransactionOption` for OCC transaction.
        
        Args:
            label (str, optional): Transaction label.
        
        Returns:
            TransactionOption: A new `TransactionOption` instance for OCC transaction.
        
        Examples:
            ```python
            import tsurugi_dbapi as tsurugi
        
            tx_option = tsurugi.TransactionOption.occ(label="OCC transaction")
            ```
        """
    @classmethod
    def ltx(cls, label: typing.Optional[builtins.str] = None, write_preserve: typing.Optional[typing.Sequence[builtins.str]] = None, inclusive_read_area: typing.Optional[typing.Sequence[builtins.str]] = None, exclusive_read_area: typing.Optional[typing.Sequence[builtins.str]] = None) -> TransactionOption:
        r"""
        Create a new `TransactionOption` for LTX transaction.
        
        Args:
            label (str, optional): Transaction label.
            write_preserve (List[str], optional): List of table names to preserve for write operations.
            inclusive_read_area (List[str], optional): List of table names to include in the read area.
            exclusive_read_area (List[str], optional): List of table names to exclude from the read area.
        
        Returns:
            TransactionOption: A new `TransactionOption` instance for LTX transaction.
        
        Examples:
            ```python
            import tsurugi_dbapi as tsurugi
        
            tx_option = tsurugi.TransactionOption.ltx(
                label="LTX transaction",
                write_preserve=["table1", "table2"],
            )
            ```
        """
    @classmethod
    def ddl(cls, label: typing.Optional[builtins.str] = None) -> TransactionOption:
        r"""
        Create a new `TransactionOption` for LTX transaction for DDL.
        
        Args:
            label (str, optional): Transaction label.
        
        Returns:
            TransactionOption: A new `TransactionOption` instance for LTX transaction for DDL.
        
        Examples:
            ```python
            import tsurugi_dbapi as tsurugi
        
            tx_option = tsurugi.TransactionOption.ddl(label="LTX transaction for DDL")
            ```
        """
    @classmethod
    def rtx(cls, label: typing.Optional[builtins.str] = None, scan_parallel: typing.Optional[builtins.int] = None) -> TransactionOption:
        r"""
        Create a new `TransactionOption` for RTX transaction.
        
        Args:
            label (str, optional): Transaction label.
            scan_parallel (int, optional): Degree of parallelism for scanning.
        
        Returns:
            TransactionOption: A new `TransactionOption` instance for RTX transaction.
        
        Examples:
            ```python
            import tsurugi_dbapi as tsurugi
        
            tx_option = tsurugi.TransactionOption.rtx(
                label="RTX transaction",
                scan_parallel=4,
            )
            ```
        """

class Warning(builtins.Exception):
    r"""
    important warning (PEP 249)
    """
    ...

@typing.final
class CommitType(enum.Enum):
    r"""
    Commit type for transaction.
    
    Attributes:
        DEFAULT: the default commit type (rely on the database settings).
        ACCEPTED: commit operation has accepted, and the transaction will never abort except system errors.
        AVAILABLE: commit data has been visible for others.
        STORED: commit data has been saved on the local disk.
        PROPAGATED: commit data has been propagated to the all suitable nodes.
    """
    DEFAULT = ...
    r"""
    the default commit type (rely on the database settings).
    """
    ACCEPTED = ...
    r"""
    commit operation has accepted, and the transaction will never abort except system errors.
    """
    AVAILABLE = ...
    r"""
    commit data has been visible for others.
    """
    STORED = ...
    r"""
    commit data has been saved on the local disk.
    """
    PROPAGATED = ...
    r"""
    commit data has been propagated to the all suitable nodes.
    """

@typing.final
class ShutdownType(enum.Enum):
    r"""
    Shutdown type for connection.
    
    Attributes:
        NOTHING: Do nothing special during shutdown.
        GRACEFUL: Waits for the ongoing requests and safely shutdown the session.
        FORCEFUL: Cancelling the ongoing requests and safely shutdown the session.
    """
    NOTHING = ...
    r"""
    Do nothing special during shutdown.
    """
    GRACEFUL = ...
    r"""
    Waits for the ongoing requests and safely shutdown the session.
    """
    FORCEFUL = ...
    r"""
    Cancelling the ongoing requests and safely shutdown the session.
    """

@typing.final
class TransactionType(enum.Enum):
    r"""
    Transaction type.
    
    Attributes:
        OCC: Optimistic concurrency control (OCC) transaction.
        LTX: Long transaction (LTX).
        RTX: Read-only transaction (RTX).
    """
    OCC = ...
    r"""
    Optimistic concurrency control (OCC) transaction.
    """
    LTX = ...
    r"""
    Long transaction (LTX).
    """
    RTX = ...
    r"""
    Read-only transaction (RTX).
    """

def connect(*args: typing.Any, **kwargs: typing.Any) -> Connection:
    r"""
    Constructor for creating a connection to the Tsurugi.
    
    Args:
        *args (Config, optional): configuration object.
        **kwargs (dict, optional): e.g. `endpoint="tcp://localhost:12345"`, `user="tsurugi"`
    
    Returns:
        Connection: Connection object.
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
    
        config = tsurugi.Config()
        config.endpoint = "tcp://localhost:12345"
        config.user = "tsurugi"
        config.password = "password"
        config.default_timeout = 30  # seconds
        with tsurugi.connect(config) as connection:
            pass
        ```
    
        ```python
        import tsurugi_dbapi as tsurugi
    
        with tsurugi.connect(
            endpoint="tcp://localhost:12345",
            user="tsurugi",
            password="password",
            default_timeout=30,  # seconds
        ) as connection:
            pass
        ```
    """

def env_logger_init(filters: builtins.str = 'tsubakuro_rust_python=info', file_path: typing.Optional[builtins.str] = None) -> None:
    r"""
    Initialize env_logger.
    
    Args:
        filters (str, optional): filter string. If ommitted, `"tsubakuro_rust_python=info"` is used.
        file_path (str, optional): log file path. If None, logs to stderr.
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
    
        tsurugi.env_logger_init("tsubakuro_rust_python=trace")
        ```
    
    Note:
        - `tsubakuro_rust_python` is the name of an internal module.
        - Any calls to `env_logger_init` or `logging_init` other than the first one are ignored.
    """

def logging_init() -> None:
    r"""
    Initialize logging.
    
    Examples:
        ```python
        import logging
        import tsurugi_dbapi as tsurugi
    
        logging.basicConfig()
        logger = logging.getLogger("_tsubakuro_rust_python")
        logger.setLevel(5)  # TRACE
    
        tsurugi.logging_init()
        ```
    
    Note:
        - `_tsubakuro_rust_python` is the name of an internal module.
        - Any calls to `env_logger_init` or `logging_init` other than the first one are ignored.
    """

