# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import decimal
import typing
__all__ = [
    "Bool",
    "Bytes",
    "Date",
    "Datetime",
    "Decimal",
    "Float32",
    "Float64",
    "Int32",
    "Int64",
    "OffsetDatetime",
    "OffsetTime",
    "Str",
    "Time",
]

@typing.final
class Bool:
    r"""
    BOOLEAN type.
    
    Attributes:
        value (Optional[bool]): boolean value. (read only)
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
    
        value = tsurugi.type_code.Bool(True)
        value = tsurugi.type_code.Bool(None)
        ```
    """
    @property
    def value(self) -> typing.Optional[builtins.bool]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[builtins.bool] = None) -> Bool:
        r"""
        Create a new `Bool`.
        """
    def __bool__(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Bytes:
    r"""
    BINARY, VARBINARY type.
    
    Attributes:
        value (Optional[bytes]): binary data. (read only)
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
    
        value = tsurugi.type_code.Bytes(b"0x01\x02\x03")
        value = tsurugi.type_code.Bytes(None)
        ```
    """
    @property
    def value(self) -> typing.Optional[builtins.list[builtins.int]]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[typing.Sequence[builtins.int]] = None) -> Bytes:
        r"""
        Create a new `Bytes`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Date:
    r"""
    DATE type.
    
    Attributes:
        value (Optional[datetime.date]): date value. (read only)
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
        import datetime
    
        value = tsurugi.type_code.Date(datetime.date(2026, 2, 24))
        value = tsurugi.type_code.Date(None)
        ```
    """
    @property
    def value(self) -> typing.Optional[datetime.date]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[datetime.date] = None) -> Date:
        r"""
        Create a new `Date`.
        """
    @classmethod
    def of(cls, year: builtins.int, month: builtins.int, day: builtins.int) -> Date:
        r"""
        Create a `Date` from year, month, and day.
        
        Args:
            year (int): year
            month (int): month (1-12)
            day (int): day (1-31)
        
        Returns:
            Date: created `Date` object
        """
    @classmethod
    def raw(cls, epoch_days: builtins.int) -> Date:
        r"""
        Create a `Date` from epoch days.
        
        Args:
            epoch_days (int): number of days offset of epoch 1970-01-01
        
        Returns:
            Date: created `Date` object
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Datetime:
    r"""
    TIMESTAMP type.
    
    Attributes:
        value (Optional[datetime.datetime]): datetime value. (read only)
        nanosecond (Optional[int]): nanosecond part of the time. (read only)
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
        import datetime
    
        value = tsurugi.type_code.Datetime(datetime.datetime(2026, 2, 24, 12, 34, 56, 123456)) # microsecond precision
        value = tsurugi.type_code.Datetime(datetime.datetime(2026, 2, 24, 12, 34, 56), 123456879) # nanosecond precision
        value = tsurugi.type_code.Datetime(None)
        ```
    """
    @property
    def value(self) -> typing.Optional[datetime.datetime]:
        r"""
        Value.
        """
    @property
    def nanosecond(self) -> typing.Optional[builtins.int]:
        r"""
        Nnanosecond.
        """
    def __new__(cls, value: typing.Optional[datetime.datetime] = None, nanosecond: typing.Optional[builtins.int] = None) -> Datetime:
        r"""
        Create a new `Datetime`.
        """
    @classmethod
    def of(cls, year: builtins.int, month: builtins.int, day: builtins.int, hour: builtins.int = 0, minute: builtins.int = 0, second: builtins.int = 0, nanosecond: builtins.int = 0) -> Datetime:
        r"""
        Create a `Datetime` from year, month, day, hour, minute, second, and nanosecond.
        
        Args:
            year (int): year
            month (int): month (1-12)
            day (int): day (1-31)
            hour (int, optional): hour (0-23)
            minute (int, optional): minute (0-59)
            second (int, optional): second (0-59)
            nanosecond (int, optional): nanosecond (0-999,999,999)
        
        Returns:
            Datetime: created `Datetime` object
        """
    @classmethod
    def raw(cls, epoch_seconds: builtins.int, nanos: builtins.int) -> Datetime:
        r"""
        Create a `Datetime` from epoch seconds and nanoseconds.
        
        Args:
            epoch_seconds (int): offset seconds from epoch (1970-01-01 00:00:00)
            nanos (int): nanosecond part of the time (0-999,999,999)
        
        Returns:
            Datetime: created `Datetime` object
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Decimal:
    r"""
    DECIMAL type.
    
    Attributes:
        value (Optional[decimal.Decimal]): decimal value. (read only)
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
        import decimal
    
        value = tsurugi.type_code.Decimal(decimal.Decimal("123.45"))
        value = tsurugi.type_code.Decimal(None)
        ```
    """
    @property
    def value(self) -> typing.Optional[decimal.Decimal]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[decimal.Decimal] = None) -> Decimal:
        r"""
        Create a new `Decimal`.
        """
    @classmethod
    def raw(cls, unscaled_value: typing.Sequence[builtins.int], exponent: builtins.int) -> Decimal:
        r"""
        Create a `Decimal` from unscaled value and exponent.
        
        Args:
            unscaled_value (bytes): unscaled value as big-endian byte array
            exponent (int): exponent
        
        Returns:
            Decimal: created `Decimal` object
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Float32:
    r"""
    REAL type.
    
    Attributes:
        value (Optional[float]): float value. (read only)
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
    
        value = tsurugi.type_code.Float32(123.5)
        value = tsurugi.type_code.Float32(None)
        ```
    """
    @property
    def value(self) -> typing.Optional[builtins.float]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[builtins.float] = None) -> Float32:
        r"""
        Create a new `Float32`.
        """
    def __float__(self) -> typing.Optional[builtins.float]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Float64:
    r"""
    DOUBLE type.
    
    Attributes:
        value (Optional[float]): float value. (read only)
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
    
        value = tsurugi.type_code.Float64(123.5)
        value = tsurugi.type_code.Float64(None)
        ```
    """
    @property
    def value(self) -> typing.Optional[builtins.float]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[builtins.float] = None) -> Float64:
        r"""
        Create a new `Float64`.
        """
    def __float__(self) -> typing.Optional[builtins.float]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Int32:
    r"""
    INT type.
    
    Attributes:
        value (Optional[int]): integer value. (read only)
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
    
        value = tsurugi.type_code.Int32(123)
        value = tsurugi.type_code.Int32(None)
        ```
    """
    @property
    def value(self) -> typing.Optional[builtins.int]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[builtins.int] = None) -> Int32:
        r"""
        Create a new `Int32`.
        """
    def __int__(self) -> typing.Optional[builtins.int]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Int64:
    r"""
    BIGINT type.
    
    Attributes:
        value (Optional[int]): integer value. (read only)
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
    
        value = tsurugi.type_code.Int64(123)
        value = tsurugi.type_code.Int64(None)
        ```
    """
    @property
    def value(self) -> typing.Optional[builtins.int]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[builtins.int] = None) -> Int64:
        r"""
        Create a new `Int64`.
        """
    def __int__(self) -> typing.Optional[builtins.int]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class OffsetDatetime:
    r"""
    TIMESTAMP WITH TIME ZONE type.
    
    Attributes:
        value (Optional[datetime.datetime]): datetime value with time zone. (read only)
        nanosecond (Optional[int]): nanosecond part of the time. (read only)
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
        import datetime
    
        JST = datetime.timezone(datetime.timedelta(hours=9))
        value = tsurugi.type_code.OffsetDatetime(datetime.datetime(2026, 2, 24, 12, 34, 56, 123456, tzinfo=JST)) # microsecond precision
        value = tsurugi.type_code.OffsetDatetime(datetime.datetime(2026, 2, 24, 12, 34, 56, tzinfo=JST), 123456879) # nanosecond precision
        value = tsurugi.type_code.OffsetDatetime(None)
        ```
    """
    @property
    def value(self) -> typing.Optional[datetime.datetime]:
        r"""
        Value.
        """
    @property
    def nanosecond(self) -> typing.Optional[builtins.int]:
        r"""
        Nnanosecond.
        """
    def __new__(cls, value: typing.Optional[datetime.datetime] = None, nanosecond: typing.Optional[builtins.int] = None) -> OffsetDatetime:
        r"""
        Create a new `OffsetDatetime`.
        """
    @classmethod
    def of(cls, year: builtins.int, month: builtins.int, day: builtins.int, hour: builtins.int = 0, minute: builtins.int = 0, second: builtins.int = 0, nanosecond: builtins.int = 0, tzinfo: typing.Optional[datetime.tzinfo] = None) -> OffsetDatetime:
        r"""
        Create a `OffsetDatetime` from year, month, day, hour, minute, second, nanosecond, and tzinfo.
        
        Args:
            year (int): year
            month (int): month (1-12)
            day (int): day (1-31)
            hour (int, optional): hour (0-23)
            minute (int, optional): minute (0-59)
            second (int, optional): second (0-59)
            nanosecond (int, optional): nanosecond (0-999,999,999)
            tzinfo (datetime.tzinfo, optional): time zone info (default: UTC)
        
        Returns:
            OffsetDatetime: created `OffsetDatetime` object
        """
    @classmethod
    def raw(cls, epoch_seconds: builtins.int, nanos: builtins.int, time_zone_offset: builtins.int) -> OffsetDatetime:
        r"""
        Create a `OffsetDatetime` from epoch seconds, nanoseconds, and time zone offset.
        
        Args:
            epoch_seconds (int): offset seconds from epoch (1970-01-01 00:00:00)
            nanos (int): nanosecond part of the time (0-999,999,999)
            time_zone_offset (int): time zone offset in minutes
        
        Returns:
            OffsetDatetime: created `OffsetDatetime` object
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class OffsetTime:
    r"""
    TIME WITH TIME ZONE type.
    
    Attributes:
        value (Optional[datetime.time]): time value with time zone. (read only)
        nanosecond (Optional[int]): nanosecond part of the time. (read only)
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
        import datetime
    
        JST = datetime.timezone(datetime.timedelta(hours=9))
        value = tsurugi.type_code.OffsetTime(datetime.time(12, 34, 56, 123456, tzinfo=JST)) # microsecond precision
        value = tsurugi.type_code.OffsetTime(datetime.time(12, 34, 56, tzinfo=JST), 123456879) # nanosecond precision
        value = tsurugi.type_code.OffsetTime(None)
        ```
    """
    @property
    def value(self) -> typing.Optional[datetime.time]:
        r"""
        Value.
        """
    @property
    def nanosecond(self) -> typing.Optional[builtins.int]:
        r"""
        Nnanosecond.
        """
    def __new__(cls, value: typing.Optional[datetime.time] = None, nanosecond: typing.Optional[builtins.int] = None) -> OffsetTime:
        r"""
        Create a new `OffsetTime`.
        """
    @classmethod
    def of(cls, hour: builtins.int = 0, minute: builtins.int = 0, second: builtins.int = 0, nanosecond: builtins.int = 0, tzinfo: typing.Optional[datetime.tzinfo] = None) -> OffsetTime:
        r"""
        Create a `OffsetTime` from hour, minute, second, nanosecond, and tzinfo.
        
        Args:
            hour (int, optional): hour (0-23)
            minute (int, optional): minute (0-59)
            second (int, optional): second (0-59)
            nanosecond (int, optional): nanosecond (0-999,999,999)
            tzinfo (datetime.tzinfo, optional): time zone info (Default: UTC)
        
        Returns:
            OffsetTime: created `OffsetTime` object
        """
    @classmethod
    def raw(cls, nanoseconds_of_day: builtins.int, time_zone_offset: builtins.int) -> OffsetTime:
        r"""
        Create a `OffsetTime` from epoch nanoseconds of day and time zone offset.
        
        Args:
            nanoseconds_of_day (int): offset nano-seconds from epoch (00:00:00) in the time zone
            time_zone_offset (int): timezone offset in minute
        
        Returns:
            OffsetTime: created `OffsetTime` object
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Str:
    r"""
    CHAR, VARCHAR type.
    
    Attributes:
        value (Optional[str]): string value. (read only)
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
    
        value = tsurugi.type_code.Str("abc")
        value = tsurugi.type_code.Str(None)
        ```
    """
    @property
    def value(self) -> typing.Optional[builtins.str]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[builtins.str] = None) -> Str:
        r"""
        Create a new `Str`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Time:
    r"""
    TIME type.
    
    Attributes:
        value (Optional[datetime.time]): time value. (read only)
        nanosecond (Optional[int]): nanosecond part of the time. (read only)
    
    Examples:
        ```python
        import tsurugi_dbapi as tsurugi
        import datetime
    
        value = tsurugi.type_code.Time(datetime.time(12, 34, 56, 123456)) # microsecond precision
        value = tsurugi.type_code.Time(datetime.time(12, 34, 56), 123456879) # nanosecond precision
        value = tsurugi.type_code.Time(None)
        ```
    """
    @property
    def value(self) -> typing.Optional[datetime.time]:
        r"""
        Value.
        """
    @property
    def nanosecond(self) -> typing.Optional[builtins.int]:
        r"""
        Nnanosecond.
        """
    def __new__(cls, value: typing.Optional[datetime.time] = None, nanosecond: typing.Optional[builtins.int] = None) -> Time:
        r"""
        Create a new `Time`.
        """
    @classmethod
    def of(cls, hour: builtins.int = 0, minute: builtins.int = 0, second: builtins.int = 0, nanosecond: builtins.int = 0) -> Time:
        r"""
        Create a `Time` from hour, minute, second, and nanosecond.
        
        Args:
            hour (int, optional): hour (0-23)
            minute (int, optional): minute (0-59)
            second (int, optional): second (0-59)
            nanosecond (int, optional): nanosecond (0-999,999,999)
        
        Returns:
            Time: created `Time` object
        """
    @classmethod
    def raw(cls, nanoseconds_of_day: builtins.int) -> Time:
        r"""
        Create a `Time` from nanoseconds of day.
        
        Args:
            nanoseconds_of_day (int): time of day (nanoseconds since 00:00:00)
        
        Returns:
            Time: created `Time` object
        """
    def __repr__(self) -> builtins.str: ...

