# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import tsubakuro_rust_python
import typing
__all__ = [
    "connect",
]

@typing.overload
def connect(*args: tsubakuro_rust_python.Config) -> tsubakuro_rust_python.Connection: ...

@typing.overload
def connect(*args: Any) -> tsubakuro_rust_python.Connection: ...

@typing.overload
def connect(**kwargs: Any) -> tsubakuro_rust_python.Connection: ...

