# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import tsubakuro_rust_python
import typing
__all__ = [
    "Column",
    "CommitOption",
    "CommitType",
    "Config",
    "Connection",
    "Cursor",
    "ShutdownOption",
    "ShutdownType",
    "TableMetadata",
    "TransactionOption",
    "TransactionType",
    "connect",
    "env_logger_init",
]

@typing.final
class Column:
    r"""
    Column metadata.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Column name.
        """
    @property
    def description(self) -> typing.Optional[builtins.str]:
        r"""
        Column description.
        """
    @property
    def type_code(self) -> builtins.str:
        r"""
        type_code.
        """
    @property
    def atom_type_code(self) -> builtins.int:
        r"""
        AtomType code.
        """
    @property
    def sql_type(self) -> builtins.str:
        r"""
        SQL type.
        """
    @property
    def sql_type_name(self) -> typing.Optional[builtins.str]:
        r"""
        SQL type name.
        """
    @property
    def length(self) -> typing.Optional[builtins.int]:
        r"""
        Length.
        """
    @property
    def precision(self) -> typing.Optional[builtins.int]:
        r"""
        Precision.
        """
    @property
    def scale(self) -> typing.Optional[builtins.int]:
        r"""
        Scale.
        """
    @property
    def nullable(self) -> typing.Optional[builtins.bool]:
        r"""
        Nullable.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CommitOption:
    r"""
    Commit option for transaction.
    """
    @property
    def commit_type(self) -> tsubakurorustpython.CommitType:
        r"""
        Commit type.
        """
    @commit_type.setter
    def commit_type(self, value: tsubakurorustpython.CommitType) -> None:
        r"""
        Commit type.
        """
    @property
    def auto_dispose(self) -> builtins.bool:
        r"""
        Auto dispose flag.
        """
    @auto_dispose.setter
    def auto_dispose(self, value: builtins.bool) -> None:
        r"""
        Auto dispose flag.
        """
    @property
    def commit_timeout(self) -> typing.Optional[builtins.int]:
        r"""
        Commit timeout in seconds.
        """
    @commit_timeout.setter
    def commit_timeout(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Commit timeout in seconds.
        """
    def __new__(cls, commit_type: CommitType = CommitType.DEFAULT, auto_dispose: builtins.bool = False, timeout: typing.Optional[builtins.int] = None) -> CommitOption:
        r"""
        Create a new `CommitOption`.
        """

@typing.final
class Config:
    r"""
    Configuration options for connecting to Tsurugi.
    """
    @property
    def endpoint(self) -> typing.Optional[builtins.str]:
        r"""
        Endpoint URL of the Tsurugi server.
        """
    @endpoint.setter
    def endpoint(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Endpoint URL of the Tsurugi server.
        """
    @property
    def user(self) -> typing.Optional[builtins.str]:
        r"""
        Username for authentication.
        """
    @user.setter
    def user(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Username for authentication.
        """
    @property
    def password(self) -> typing.Optional[builtins.str]:
        r"""
        Password for authentication.
        """
    @password.setter
    def password(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Password for authentication.
        """
    @property
    def auth_token(self) -> typing.Optional[builtins.str]:
        r"""
        Authentication token.
        """
    @auth_token.setter
    def auth_token(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Authentication token.
        """
    @property
    def credentials(self) -> typing.Optional[builtins.str]:
        r"""
        Path to credentials file.
        """
    @credentials.setter
    def credentials(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Path to credentials file.
        """
    @property
    def transaction_option(self) -> typing.Optional[TransactionOption]:
        r"""
        Transaction option.
        """
    @transaction_option.setter
    def transaction_option(self, value: typing.Optional[TransactionOption]) -> None:
        r"""
        Transaction option.
        """
    @property
    def commit_option(self) -> typing.Optional[CommitOption]:
        r"""
        Commit option.
        """
    @commit_option.setter
    def commit_option(self, value: typing.Optional[CommitOption]) -> None:
        r"""
        Commit option.
        """
    @property
    def shutdown_option(self) -> typing.Optional[ShutdownOption]:
        r"""
        Shutdown option.
        """
    @shutdown_option.setter
    def shutdown_option(self, value: typing.Optional[ShutdownOption]) -> None:
        r"""
        Shutdown option.
        """
    @property
    def default_timeout(self) -> typing.Optional[builtins.int]:
        r"""
        Default timeout in seconds.
        """
    @default_timeout.setter
    def default_timeout(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Default timeout in seconds.
        """
    def __new__(cls, *args: typing.Any, **kwargs: typing.Any) -> Config:
        r"""
        Create a new `Config`.
        """
    def set(self, *args: typing.Any, **kwargs: typing.Any) -> None:
        r"""
        Set configuration options.
        """
    def merge(self, other: Config) -> None:
        r"""
        Merge another `Config` into this one.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Connection:
    r"""
    Connection to Tsurugi.
    """
    @property
    def closed(self) -> builtins.bool: ...
    @transaction_option.setter
    def transaction_option(self, value: TransactionOption) -> None:
        r"""
        Set transaction option.
        
        # Parameters
        - `option` - [`TransactionOption`] object.
        """
    @commit_option.setter
    def commit_option(self, value: CommitOption) -> None:
        r"""
        Set commit option.
        
        # Parameters
        - `option` - [`CommitOption`] object.
        """
    @shutdown_option.setter
    def shutdown_option(self, value: ShutdownOption) -> None:
        r"""
        Set shutdown option.
        
        # Parameters
        - `option` - [`ShutdownOption`] object.
        """
    def list_tables(self) -> builtins.list[builtins.str]:
        r"""
        List table names.
        
        # Returns
        List of table names.
        """
    def get_table_metadata(self, table_name: builtins.str) -> TableMetadata:
        r"""
        Get table metadata.
        
        # Parameters
        - `table_name` - table name.
        
        # Returns
        Table metadata.
        
        # Errors
        Raises an exception if the table does not exist.
        """
    def find_table_metadata(self, table_name: builtins.str) -> typing.Optional[TableMetadata]:
        r"""
        Find table metadata.
        
        # Parameters
        - `table_name` - table name.
        
        # Returns
        Table metadata, or None if the table does not exist.
        """
    def cursor(self) -> Cursor:
        r"""
        Create a new cursor object using the connection.
        
        # Returns
        [`Cursor`] object.
        """
    def commit(self, option: typing.Optional[CommitOption] = None) -> None:
        r"""
        Commit the current transaction.
        
        # Parameters
        - `option` - Optional [`CommitOption`] object to override the connection's commit option.
        """
    def rollback(self) -> None:
        r"""
        Rollback the current transaction.
        """
    def __enter__(self, slf: Connection) -> Connection:
        r"""
        Enter the runtime context related to this object.
        """
    def __exit__(self, _exc_type: typing.Optional[typing.Any], _exc_value: typing.Optional[typing.Any], _traceback: typing.Optional[typing.Any]) -> None:
        r"""
        Exit the runtime context related to this object.
        """
    def close(self) -> None:
        r"""
        Close the connection.
        """

@typing.final
class Cursor:
    r"""
    Cursor object for executing SQL statements and fetching results.
    """
    @property
    def executemany_async(self) -> builtins.bool: ...
    @executemany_async.setter
    def executemany_async(self, value: builtins.bool) -> None: ...
    @property
    def arraysize(self) -> builtins.int: ...
    @arraysize.setter
    def arraysize(self, value: builtins.int) -> None:
        r"""
        Set the number of rows to fetch at a time with [`fetchmany`].
        
        # Parameters
        - `size` - Number of rows to fetch at a time. If less than 1 is specified, use 1.
        """
    @property
    def rowcount(self) -> builtins.int: ...
    @property
    def closed(self) -> builtins.bool: ...
    @property
    def description(self) -> Optional[Sequence[Tuple[
        str,           # name
        int,           # type_code
        None,          # display_size
        Optional[int], # internal_size
        Optional[int], # precision
        Optional[int], # scale
        Optional[bool] # null_ok
    ]]]:
        r"""
        description of the query result set.
        
        # Returns
        A sequence of 7-item sequences. Each of these sequences contains information describing one result column.
         The 7 items are: (name, type_code, display_size, internal_size, precision, scale, null_ok)
        """
    @property
    def rownumber(self) -> typing.Optional[builtins.int]:
        r"""
        Current row number (0-based).
        
        # Returns
        An optional integer representing the current row number. If no rows have been fetched, returns `None`.
        """
    def execute(self, operation: builtins.str, parameters: typing.Optional[typing.Any] = None) -> None:
        r"""
        Execute a SQL statement.
        
        # Parameters
        - `operation` - SQL statement to be executed.
        - `parameters` - parameters for the SQL statement.
        """
    def prepare(self, operation: builtins.str, parameters: typing.Any) -> None:
        r"""
        Prepare a SQL statement for execution.
        
        # Parameters
        - `operation` - SQL statement to be prepared.
        - `parameters` - parameters for the SQL statement.
        """
    def executemany(self, operation: builtins.str, seq_of_parameters: typing.Any) -> None:
        r"""
        Execute a prepared SQL statement multiple times.
        
        # Parameters
        - `operation` - SQL statement to be executed.
        - `seq_of_parameters` - sequence of parameters for the SQL statement.
        """
    def fetchone(self) -> typing.Optional[tuple]:
        r"""
        Fetch the next row of a query result set.
        
        # Returns
        A single sequence representing the next row of the result set, or `None` if no more data is available.
        """
    def next(self) -> tuple:
        r"""
        Fetch the next row of a query result set.
        
        # Returns
        A single sequence representing the next row of the result set.
        
        # Errors
        Raises `StopIteration` when no more data is available.
        """
    def fetchmany(self, size: typing.Optional[builtins.int] = None) -> builtins.list[tuple]:
        r"""
        Fetch the next set of rows of a query result set.
        
        # Parameters
        - `size` - Number of rows to fetch. If not specified, use the cursor's `arraysize` attribute.
        
        # Returns
        A list of sequences, each representing a row of the result set.
        """
    def fetchall(self) -> builtins.list[tuple]:
        r"""
        Fetch all (remaining) rows of a query result set.
        
        # Returns
        A list of sequences, each representing a row of the result set.
        """
    def callproc(self, _procname: builtins.str, _parameters: typing.Optional[typing.Any] = None) -> None:
        r"""
        Not supported in this implementation.
        """
    def nextset(self) -> None:
        r"""
        Not supported in this implementation.
        """
    def setinputsizes(self, _sizes: typing.Any) -> None:
        r"""
        This method is a no-op in this implementation.
        """
    def setoutputsize(self, _size: builtins.int, _column: typing.Optional[builtins.int] = None) -> None:
        r"""
        This method is a no-op in this implementation.
        """
    def __iter__(self, slf: Cursor) -> Cursor:
        r"""
        Iterator protocol: return the iterator object itself.
        """
    def __next__(self) -> tuple:
        r"""
        Iterator protocol: return the next row in the result set.
        """
    def __enter__(self, slf: Cursor) -> Cursor:
        r"""
        Enter the runtime context related to this object.
        """
    def __exit__(self, _exc_type: typing.Optional[typing.Any], _exc_value: typing.Optional[typing.Any], _traceback: typing.Optional[typing.Any]) -> None:
        r"""
        Exit the runtime context related to this object.
        """
    def clear(self) -> None:
        r"""
        Clear the current query result and prepared statements.
        """
    def close(self) -> None:
        r"""
        Close the cursor.
        """

@typing.final
class ShutdownOption:
    r"""
    Shutdown option for connection.
    """
    @property
    def shutdown_type(self) -> tsubakurorustpython.ShutdownType:
        r"""
        Shutdown type.
        """
    @shutdown_type.setter
    def shutdown_type(self, value: tsubakurorustpython.ShutdownType) -> None:
        r"""
        Shutdown type.
        """
    @property
    def shutdown_timeout(self) -> typing.Optional[builtins.int]:
        r"""
        Shutdown timeout in seconds.
        """
    @shutdown_timeout.setter
    def shutdown_timeout(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Shutdown timeout in seconds.
        """
    def __new__(cls, shutdown_type: ShutdownType = ShutdownType.GRACEFUL, timeout: typing.Optional[builtins.int] = None) -> ShutdownOption:
        r"""
        Create a new `ShutdownOption`.
        """

@typing.final
class TableMetadata:
    r"""
    Table metadata.
    """
    @property
    def database_name(self) -> builtins.str:
        r"""
        Database name.
        """
    @property
    def schema_name(self) -> builtins.str:
        r"""
        Schema name.
        """
    @property
    def table_name(self) -> builtins.str:
        r"""
        Table name.
        """
    @property
    def table_description(self) -> typing.Optional[builtins.str]:
        r"""
        Table description.
        """
    @property
    def columns(self) -> builtins.list[Column]:
        r"""
        Columns metadata.
        """
    @property
    def description(self) -> Optional[Sequence[Tuple[
        str,           # name
        int,           # type_code
        None,          # display_size
        Optional[int], # internal_size
        Optional[int], # precision
        Optional[int], # scale
        Optional[bool] # null_ok
    ]]]:
        r"""
        Columns description.
        """
    @property
    def primary_keys(self) -> builtins.list[builtins.str]:
        r"""
        Primary keys.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class TransactionOption:
    r"""
    Transaction option.
    """
    @property
    def transaction_type(self) -> tsubakurorustpython.TransactionType:
        r"""
        Transaction type.
        """
    @transaction_type.setter
    def transaction_type(self, value: tsubakurorustpython.TransactionType) -> None:
        r"""
        Transaction type.
        """
    @property
    def label(self) -> typing.Optional[builtins.str]:
        r"""
        Transaction label.
        """
    @label.setter
    def label(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Transaction label.
        """
    @property
    def include_ddl(self) -> builtins.bool:
        r"""
        Include DDL flag.
        """
    @include_ddl.setter
    def include_ddl(self, value: builtins.bool) -> None:
        r"""
        Include DDL flag.
        """
    @property
    def write_preserve(self) -> typing.Optional[builtins.list[builtins.str]]:
        r"""
        Write preserve.
        """
    @write_preserve.setter
    def write_preserve(self, value: typing.Optional[builtins.list[builtins.str]]) -> None:
        r"""
        Write preserve.
        """
    @property
    def inclusive_read_area(self) -> typing.Optional[builtins.list[builtins.str]]:
        r"""
        Inclusive read area.
        """
    @inclusive_read_area.setter
    def inclusive_read_area(self, value: typing.Optional[builtins.list[builtins.str]]) -> None:
        r"""
        Inclusive read area.
        """
    @property
    def exclusive_read_area(self) -> typing.Optional[builtins.list[builtins.str]]:
        r"""
        Exclusive read area.
        """
    @exclusive_read_area.setter
    def exclusive_read_area(self, value: typing.Optional[builtins.list[builtins.str]]) -> None:
        r"""
        Exclusive read area.
        """
    @property
    def scan_parallel(self) -> typing.Optional[builtins.int]:
        r"""
        Scan parallel.
        """
    @scan_parallel.setter
    def scan_parallel(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Scan parallel.
        """
    @property
    def begin_timeout(self) -> typing.Optional[builtins.int]:
        r"""
        Begin transaction timeout in seconds.
        """
    @begin_timeout.setter
    def begin_timeout(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Begin transaction timeout in seconds.
        """
    def __new__(cls, r#type: TransactionType = TransactionType.OCC) -> TransactionOption: ...

@typing.final
class CommitType(enum.Enum):
    r"""
    Commit type for transaction.
    """
    DEFAULT = ...
    r"""
    the default commit type (rely on the database settings).
    """
    ACCEPTED = ...
    r"""
    commit operation has accepted, and the transaction will never abort except system errors.
    """
    AVAILABLE = ...
    r"""
    commit data has been visible for others.
    """
    STORED = ...
    r"""
    commit data has been saved on the local disk.
    """
    PROPAGATED = ...
    r"""
    commit data has been propagated to the all suitable nodes.
    """

@typing.final
class ShutdownType(enum.Enum):
    r"""
    Shutdown type for connection.
    """
    NOTHING = ...
    r"""
    Do nothing special during shutdown.
    """
    GRACEFUL = ...
    r"""
    Waits for the ongoing requests and safely shutdown the session.
    """
    FORCEFUL = ...
    r"""
    Cancelling the ongoing requests and safely shutdown the session.
    """

@typing.final
class TransactionType(enum.Enum):
    r"""
    Transaction type.
    """
    OCC = ...
    LTX = ...
    RTX = ...

@typing.overload
def connect(*args: typing.Any, **kwargs: typing.Any) -> tsubakurorustpython.Connection:
    r"""
    Constructor for creating a connection to the Tsurugi.
    
    # Parameters
    - `args` - see [`Config`].
    - `kwargs` - e.g. `endpoint="tcp://localhost:12345"`, `user="tsurugi"``
    
    # Returns
    [`Connection`] object.
    """

@typing.overload
def connect(*args: tsubakuro_rust_python.Config) -> tsubakuro_rust_python.Connection: ...

@typing.overload
def connect(*args: Any) -> tsubakuro_rust_python.Connection: ...

@typing.overload
def connect(**kwargs: Any) -> tsubakuro_rust_python.Connection: ...

def env_logger_init(filters: builtins.str = 'tsubakuro_rust_python=info', file_path: typing.Optional[builtins.str] = None) -> None:
    r"""
    Initialize env_logger.
    
    # Parameters
    - `filters` - filter string. (e.g. "tsubakuro_rust_python=trace")
                  If ommitted, "tsubakuro_rust_python=info" is used.
    - `file_path` - log file path. If None, logs to stderr.
    
    Calls to `env_logger_init` other than the first one are ignored.
    """

