# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import decimal
import enum
import tsubakuro_rust_python
import typing
__all__ = [
    "Bool",
    "Bytes",
    "Column",
    "CommitOption",
    "CommitType",
    "Config",
    "Connection",
    "Cursor",
    "Date",
    "Datetime",
    "Decimal",
    "Float32",
    "Float64",
    "Int32",
    "Int64",
    "OffsetDatetime",
    "OffsetTime",
    "ShutdownOption",
    "ShutdownType",
    "Str",
    "TableMetadata",
    "Time",
    "TransactionOption",
    "TransactionType",
    "connect",
    "env_logger_init",
]

@typing.final
class Bool:
    r"""
    BOOLEAN type.
    
    Attributes:
        value (Optional[bool]): boolean value. (read only)
    """
    @property
    def value(self) -> typing.Optional[builtins.bool]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[builtins.bool] = None) -> Bool:
        r"""
        Create a new `Bool`.
        """
    def __bool__(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Bytes:
    r"""
    BINARY, VARBINARY type.
    
    Attributes:
        value (Optional[bytes]): binary data. (read only)
    """
    @property
    def value(self) -> typing.Optional[builtins.list[builtins.int]]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[typing.Sequence[builtins.int]] = None) -> Bytes:
        r"""
        Create a new `Bytes`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Column:
    r"""
    Column metadata.
    
    Attributes:
        name (str): Column name. (read only)
        description (Optional[str]): Column description. (read only)
        type_code (str): Type code. (read only)
        atom_type_code (int): AtomType code. -1 if unknown. (read only)
        sql_type (str): SQL type. (read only)
        sql_type_name (Optional[str]): SQL type name. (read only)
        length (Optional[int]): Length for string types. (read only)
        precision (Optional[int]): Precision for numeric types. (read only)
        scale (Optional[int]): Scale for numeric types. (read only)
        nullable (Optional[bool]): Nullable flag. (read only)
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Column name.
        """
    @property
    def description(self) -> typing.Optional[builtins.str]:
        r"""
        Column description.
        """
    @property
    def type_code(self) -> builtins.str:
        r"""
        type_code.
        """
    @property
    def atom_type_code(self) -> builtins.int:
        r"""
        AtomType code.
        """
    @property
    def sql_type(self) -> builtins.str:
        r"""
        SQL type.
        """
    @property
    def sql_type_name(self) -> typing.Optional[builtins.str]:
        r"""
        SQL type name.
        """
    @property
    def length(self) -> typing.Optional[builtins.int]:
        r"""
        Length.
        """
    @property
    def precision(self) -> typing.Optional[builtins.int]:
        r"""
        Precision.
        """
    @property
    def scale(self) -> typing.Optional[builtins.int]:
        r"""
        Scale.
        """
    @property
    def nullable(self) -> typing.Optional[builtins.bool]:
        r"""
        Nullable.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CommitOption:
    r"""
    Commit option for transaction.
    
    Attributes:
        commit_type (CommitType): Commit type. Default is `CommitType.DEFAULT`.
        auto_dispose (bool): Auto dispose flag. Default is `False`.
        commit_timeout (int): Commit timeout in seconds.
    
    Examples:
        ```python
        import tsubakuro_rust_python as tsurugi
    
        commit_option = tsurugi.CommitOption(tsurugi.CommitType.DEFAULT, False, 60)
        ```
    """
    @property
    def commit_type(self) -> tsubakurorustpython.CommitType:
        r"""
        Commit type.
        """
    @commit_type.setter
    def commit_type(self, value: tsubakurorustpython.CommitType) -> None:
        r"""
        Commit type.
        """
    @property
    def auto_dispose(self) -> builtins.bool:
        r"""
        Auto dispose flag.
        """
    @auto_dispose.setter
    def auto_dispose(self, value: builtins.bool) -> None:
        r"""
        Auto dispose flag.
        """
    @property
    def commit_timeout(self) -> typing.Optional[builtins.int]:
        r"""
        Commit timeout in seconds.
        """
    @commit_timeout.setter
    def commit_timeout(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Commit timeout in seconds.
        """
    def __new__(cls, commit_type: CommitType = CommitType.DEFAULT, auto_dispose: builtins.bool = False, timeout: typing.Optional[builtins.int] = None) -> CommitOption:
        r"""
        Create a new `CommitOption`.
        """

@typing.final
class Config:
    r"""
    Configuration options for connecting to Tsurugi.
    
    Attributes:
        endpoint (str): Endpoint URL of the Tsurugi server.
        user (str): Username for authentication.
        password (str): Password for authentication.
        auth_token (str): Authentication token.
        credentials (str): Path to credentials file.
        transaction_option (TransactionOption): Transaction option.
        commit_option (CommitOption): Commit option.
        shutdown_option (ShutdownOption): Shutdown option.
        default_timeout (int): Default timeout in seconds.
    
    Examples:
        ```python
        import tsubakuro_rust_python as tsurugi
    
        config = tsurugi.Config()
        config.endpoint = "tcp://localhost:12345"
        config.user = "tsurugi"
        config.password = "password"
        config.default_timeout = 30  # seconds
        ```
    
        ```python
        import tsubakuro_rust_python as tsurugi
    
        config = tsurugi.Config(
            endpoint="tcp://localhost:12345",
            user="tsurugi",
            password="password",
            default_timeout=30,  # seconds
        )
        ```
    """
    @property
    def endpoint(self) -> typing.Optional[builtins.str]:
        r"""
        Endpoint URL of the Tsurugi server.
        """
    @endpoint.setter
    def endpoint(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Endpoint URL of the Tsurugi server.
        """
    @property
    def user(self) -> typing.Optional[builtins.str]:
        r"""
        Username for authentication.
        """
    @user.setter
    def user(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Username for authentication.
        """
    @property
    def password(self) -> typing.Optional[builtins.str]:
        r"""
        Password for authentication.
        """
    @password.setter
    def password(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Password for authentication.
        """
    @property
    def auth_token(self) -> typing.Optional[builtins.str]:
        r"""
        Authentication token.
        """
    @auth_token.setter
    def auth_token(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Authentication token.
        """
    @property
    def credentials(self) -> typing.Optional[builtins.str]:
        r"""
        Path to credentials file.
        """
    @credentials.setter
    def credentials(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Path to credentials file.
        """
    @property
    def transaction_option(self) -> typing.Optional[TransactionOption]:
        r"""
        Transaction option.
        """
    @transaction_option.setter
    def transaction_option(self, value: typing.Optional[TransactionOption]) -> None:
        r"""
        Transaction option.
        """
    @property
    def commit_option(self) -> typing.Optional[CommitOption]:
        r"""
        Commit option.
        """
    @commit_option.setter
    def commit_option(self, value: typing.Optional[CommitOption]) -> None:
        r"""
        Commit option.
        """
    @property
    def shutdown_option(self) -> typing.Optional[ShutdownOption]:
        r"""
        Shutdown option.
        """
    @shutdown_option.setter
    def shutdown_option(self, value: typing.Optional[ShutdownOption]) -> None:
        r"""
        Shutdown option.
        """
    @property
    def default_timeout(self) -> typing.Optional[builtins.int]:
        r"""
        Default timeout in seconds.
        """
    @default_timeout.setter
    def default_timeout(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Default timeout in seconds.
        """
    def __new__(cls, *args: typing.Any, **kwargs: typing.Any) -> Config:
        r"""
        Create a new `Config`.
        
        Args:
            *args (Config | TransactionOption | CommitOption | ShutdownOption | str, optional): other configuration object.
            **kwargs (dict, optional): e.g. `endpoint="tcp://localhost:12345"`, `user="tsurugi"`
        
        Returns:
            Config: configuration object.
        """
    def set(self, *args: typing.Any, **kwargs: typing.Any) -> None:
        r"""
        Set configuration options.
        
        Args:
            *args (Config | TransactionOption | CommitOption | ShutdownOption | str, optional): other configuration object.
            **kwargs (dict, optional): e.g. `endpoint="tcp://localhost:12345"`, `user="tsurugi"`
        """
    def merge(self, other: Config) -> None:
        r"""
        Merge another `Config` into this one.
        
        Args:
            other (Config): other configuration object.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Connection:
    r"""
    Connection to Tsurugi.
    
    Attributes:
        transaction_option (TransactionOption): Transaction option. (write only)
        commit_option (CommitOption): Commit option. (write only)
        shutdown_option (ShutdownOption): Shutdown option. (write only)
        closed (bool): Whether the connection is closed. (read only)
    """
    @property
    def closed(self) -> builtins.bool:
        r"""
        Whether the connection is closed.
        """
    @transaction_option.setter
    def transaction_option(self, value: TransactionOption) -> None:
        r"""
        Transaction option.
        """
    @commit_option.setter
    def commit_option(self, value: CommitOption) -> None:
        r"""
        Commit option.
        """
    @shutdown_option.setter
    def shutdown_option(self, value: ShutdownOption) -> None:
        r"""
        Shutdown option.
        """
    def list_tables(self) -> builtins.list[builtins.str]:
        r"""
        List table names.
        
        Returns:
            List[str]: List of table names.
        
        Examples:
            ```python
            table_names = connection.list_tables()
            ```
        """
    def get_table_metadata(self, table_name: builtins.str) -> TableMetadata:
        r"""
        Get table metadata.
        
        Args:
            table_name (str): Table name.
        
        Returns:
           TableMetadata: Table metadata.
        
        Raises:
            TargetNotFoundException: If the table does not exist.
        
        Examples:
            ```python
            metadata = connection.get_table_metadata("my_table")
            ```
        """
    def find_table_metadata(self, table_name: builtins.str) -> typing.Optional[TableMetadata]:
        r"""
        Find table metadata.
        
        Args:
            table_name (str): Table name.
        
        Returns:
            Optional[TableMetadata]: Table metadata, or None if the table does not exist.
        
        Examples:
            ```python
            metadata = connection.find_table_metadata("my_table")
            ```
        """
    def cursor(self) -> Cursor:
        r"""
        Create a new cursor object using the connection.
        
        Returns:
            Cursor: Cursor object.
        
        Examples:
            ```python
            with connection.cursor() as cursor:
               pass
            ```
        """
    def commit(self, option: typing.Optional[CommitOption] = None) -> None:
        r"""
        Commit the current transaction.
        
        Args:
            option (CommitOption, optional): CommitOption object.
        
        Examples:
            ```python
            connection.commit()
            ```
        """
    def rollback(self) -> None:
        r"""
        Rollback the current transaction.
        
        Examples:
            ```python
            connection.rollback()
            ```
        """
    def __enter__(self, slf: Connection) -> Connection:
        r"""
        Enter the runtime context related to this object.
        """
    def __exit__(self, _exc_type: typing.Optional[typing.Any], _exc_value: typing.Optional[typing.Any], _traceback: typing.Optional[typing.Any]) -> None:
        r"""
        Exit the runtime context related to this object.
        """
    def close(self) -> None:
        r"""
        Close the connection.
        """

@typing.final
class Cursor:
    r"""
    Cursor object for executing SQL statements and fetching results.
    
    Attributes:
        description (Optional[Sequence[Tuple[str, str, None, Optional[int], Optional[int], Optional[int], Optional[bool]]]]): Description of the query result set.
            `(name, type_code, display_size, internal_size, precision, scale, null_ok)`.  (read only)
        arraysize (int): Number of rows to fetch at a time with `Cursor.fetchmany()`. Default is 1.
        rowcount (int): Number of rows affected by the last `Cursor.execute*()` method. -1 if not applicable. (read only)
        closed (bool): Whether the cursor is closed. (read only)
    """
    @property
    def executemany_async(self) -> builtins.bool:
        r"""
        Whether to execute `Cursor.executemany()` asynchronously. Default is `True`.
        """
    @executemany_async.setter
    def executemany_async(self, value: builtins.bool) -> None:
        r"""
        Whether to execute `Cursor.executemany()` asynchronously. Default is `True`.
        """
    @property
    def arraysize(self) -> builtins.int:
        r"""
        Number of rows to fetch at a time with `Cursor.fetchmany()`.
        """
    @arraysize.setter
    def arraysize(self, value: builtins.int) -> None:
        r"""
        Number of rows to fetch at a time with `Cursor.fetchmany()`.
        """
    @property
    def rowcount(self) -> builtins.int:
        r"""
        Number of rows affected by the last `Cursor.execute*()` method.
        """
    @property
    def closed(self) -> builtins.bool:
        r"""
        Whether the cursor is closed.
        """
    @property
    def description(self) -> Optional[Sequence[Tuple[
        str,           # name
        str,           # type_code
        None,          # display_size
        Optional[int], # internal_size
        Optional[int], # precision
        Optional[int], # scale
        Optional[bool] # null_ok
    ]]]:
        r"""
        Description of the query result set.
        """
    @property
    def rownumber(self) -> typing.Optional[builtins.int]:
        r"""
        Current row number (0-based).
        """
    def execute(self, operation: builtins.str, parameters: typing.Optional[typing.Any] = None) -> None:
        r"""
        Execute a SQL statement.
        
        Args:
            operation (str): SQL statement to be executed.
            parameters (Tuple[Any, ...] | dict[str, Any], optional): Parameters for the SQL statement.
        """
    def prepare(self, operation: builtins.str, parameters: typing.Any) -> None:
        r"""
        Prepare a SQL statement for execution.
        
        Args:
            operation (str): SQL statement to be prepared.
            parameters (Tuple[Any, ...] | dict[str, Any]): Parameters for the SQL statement.
        """
    def executemany(self, operation: builtins.str, seq_of_parameters: typing.Any) -> None:
        r"""
        Execute a prepared SQL statement multiple times.
        
        Args:
            operation (str): SQL statement to be executed.
            seq_of_parameters (Sequence[Tuple[Any, ...] | dict[str, Any]]): Sequence of parameters for the SQL statement.
        """
    def fetchone(self) -> typing.Optional[tuple]:
        r"""
        Fetch the next row of a query result set.
        
        Returns:
              Optional[Tuple[Any, ...]]: A single sequence representing the next row of the result set, or `None` if no more data is available.
        """
    def next(self) -> tuple:
        r"""
        Fetch the next row of a query result set.
        
        Returns:
             Tuple[Any, ...]: A single sequence representing the next row of the result set.
        
        Raises:
            StopIteration: When no more data is available.
        """
    def fetchmany(self, size: typing.Optional[builtins.int] = None) -> builtins.list[tuple]:
        r"""
        Fetch the next set of rows of a query result set.
        
        Args:
            size (int, optional) - Number of rows to fetch. If not specified, use the cursor's `arraysize` attribute.
        
        Returns:
             List[Tuple[Any, ...]]: A list of sequences, each representing a row of the result set.
        """
    def fetchall(self) -> builtins.list[tuple]:
        r"""
        Fetch all (remaining) rows of a query result set.
        
        Returns:
             List[Tuple[Any, ...]]: A list of sequences, each representing a row of the result set.
        """
    def callproc(self, _procname: builtins.str, _parameters: typing.Optional[typing.Any] = None) -> None:
        r"""
        Not supported in this implementation.
        """
    def nextset(self) -> None:
        r"""
        Not supported in this implementation.
        """
    def setinputsizes(self, _sizes: typing.Any) -> None:
        r"""
        This method is a no-op in this implementation.
        """
    def setoutputsize(self, _size: builtins.int, _column: typing.Optional[builtins.int] = None) -> None:
        r"""
        This method is a no-op in this implementation.
        """
    def __iter__(self, slf: Cursor) -> Cursor:
        r"""
        Iterator protocol: return the iterator object itself.
        """
    def __next__(self) -> tuple:
        r"""
        Iterator protocol: return the next row in the result set.
        """
    def __enter__(self, slf: Cursor) -> Cursor:
        r"""
        Enter the runtime context related to this object.
        """
    def __exit__(self, _exc_type: typing.Optional[typing.Any], _exc_value: typing.Optional[typing.Any], _traceback: typing.Optional[typing.Any]) -> None:
        r"""
        Exit the runtime context related to this object.
        """
    def clear(self) -> None:
        r"""
        Clear the current query result and prepared statements.
        """
    def close(self) -> None:
        r"""
        Close the cursor.
        """

@typing.final
class Date:
    r"""
    DATE type.
    
    Attributes:
        value (Optional[datetime.date]): date value. (read only)
    """
    @property
    def value(self) -> typing.Optional[datetime.date]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[datetime.date] = None) -> Date:
        r"""
        Create a new `Date`.
        """
    @classmethod
    def of(cls, year: builtins.int, month: builtins.int, day: builtins.int) -> Date:
        r"""
        Create a `Date` from year, month, and day.
        
        Args:
            year (int): year
            month (int): month (1-12)
            day (int): day (1-31)
        
        Returns:
            Date: created `Date` object
        """
    @classmethod
    def raw(cls, epoch_days: builtins.int) -> Date:
        r"""
        Create a `Date` from epoch days.
        
        Args:
            epoch_days (int): number of days offset of epoch 1970-01-01
        
        Returns:
            Date: created `Date` object
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Datetime:
    r"""
    TIMESTAMP type.
    
    Attributes:
        value (Optional[datetime.datetime]): datetime value. (read only)
        nanosecond (Optional[int]): nanosecond part of the time. (read only)
    """
    @property
    def value(self) -> typing.Optional[datetime.datetime]:
        r"""
        Value.
        """
    @property
    def nanosecond(self) -> typing.Optional[builtins.int]:
        r"""
        Nnanosecond.
        """
    def __new__(cls, value: typing.Optional[datetime.datetime] = None, nanosecond: typing.Optional[builtins.int] = None) -> Datetime:
        r"""
        Create a new `Datetime`.
        """
    @classmethod
    def of(cls, year: builtins.int, month: builtins.int, day: builtins.int, hour: builtins.int = 0, minute: builtins.int = 0, second: builtins.int = 0, nanosecond: builtins.int = 0) -> Datetime:
        r"""
        Create a `Datetime` from year, month, day, hour, minute, second, and nanosecond.
        
        Args:
            year (int): year
            month (int): month (1-12)
            day (int): day (1-31)
            hour (int, optional): hour (0-23)
            minute (int, optional): minute (0-59)
            second (int, optional): second (0-59)
            nanosecond (int, optional): nanosecond (0-999,999,999)
        
        Returns:
            Datetime: created `Datetime` object
        """
    @classmethod
    def raw(cls, epoch_seconds: builtins.int, nanos: builtins.int) -> Datetime:
        r"""
        Create a `Datetime` from epoch seconds and nanoseconds.
        
        Args:
            epoch_seconds (int): offset seconds from epoch (1970-01-01 00:00:00)
            nanos (int): nanosecond part of the time (0-999,999,999)
        
        Returns:
            Datetime: created `Datetime` object
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Decimal:
    r"""
    DECIMAL type.
    
    Attributes:
        value (Optional[decimal.Decimal]): decimal value. (read only)
    """
    @property
    def value(self) -> typing.Optional[decimal.Decimal]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[decimal.Decimal] = None) -> Decimal:
        r"""
        Create a new `Decimal`.
        """
    @classmethod
    def raw(cls, unscaled_value: typing.Sequence[builtins.int], exponent: builtins.int) -> Decimal:
        r"""
        Create a `Decimal` from unscaled value and exponent.
        
        Args:
            unscaled_value (bytes): unscaled value as big-endian byte array
            exponent (int): exponent
        
        Returns:
            Decimal: created `Decimal` object
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Float32:
    r"""
    REAL type.
    
    Attributes:
        value (Optional[float]): float value. (read only)
    """
    @property
    def value(self) -> typing.Optional[builtins.float]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[builtins.float] = None) -> Float32:
        r"""
        Create a new `Float32`.
        """
    def __float__(self) -> typing.Optional[builtins.float]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Float64:
    r"""
    DOUBLE type.
    
    Attributes:
        value (Optional[float]): float value. (read only)
    """
    @property
    def value(self) -> typing.Optional[builtins.float]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[builtins.float] = None) -> Float64:
        r"""
        Create a new `Float64`.
        """
    def __float__(self) -> typing.Optional[builtins.float]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Int32:
    r"""
    INT type.
    
    Attributes:
        value (Optional[int]): integer value. (read only)
    """
    @property
    def value(self) -> typing.Optional[builtins.int]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[builtins.int] = None) -> Int32:
        r"""
        Create a new `Int32`.
        """
    def __int__(self) -> typing.Optional[builtins.int]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Int64:
    r"""
    BIGINT type.
    
    Attributes:
        value (Optional[int]): integer value. (read only)
    """
    @property
    def value(self) -> typing.Optional[builtins.int]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[builtins.int] = None) -> Int64:
        r"""
        Create a new `Int64`.
        """
    def __int__(self) -> typing.Optional[builtins.int]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class OffsetDatetime:
    r"""
    TIMESTAMP WITH TIME ZONE type.
    
    Attributes:
        value (Optional[datetime.datetime]): datetime value with time zone. (read only)
        nanosecond (Optional[int]): nanosecond part of the time. (read only)
    """
    @property
    def value(self) -> typing.Optional[datetime.datetime]:
        r"""
        Value.
        """
    @property
    def nanosecond(self) -> typing.Optional[builtins.int]:
        r"""
        Nnanosecond.
        """
    def __new__(cls, value: typing.Optional[datetime.datetime] = None, nanosecond: typing.Optional[builtins.int] = None) -> OffsetDatetime:
        r"""
        Create a new `OffsetDatetime`.
        """
    @classmethod
    def of(cls, year: builtins.int, month: builtins.int, day: builtins.int, hour: builtins.int = 0, minute: builtins.int = 0, second: builtins.int = 0, nanosecond: builtins.int = 0, tzinfo: typing.Optional[datetime.tzinfo] = None) -> OffsetDatetime:
        r"""
        Create a `OffsetDatetime` from year, month, day, hour, minute, second, nanosecond, and tzinfo.
        
        Args:
            year (int): year
            month (int): month (1-12)
            day (int): day (1-31)
            hour (int, optional): hour (0-23)
            minute (int, optional): minute (0-59)
            second (int, optional): second (0-59)
            nanosecond (int, optional): nanosecond (0-999,999,999)
            tzinfo (datetime.tzinfo, optional): time zone info (default: UTC)
        
        Returns:
            OffsetDatetime: created `OffsetDatetime` instance
        """
    @classmethod
    def raw(cls, epoch_seconds: builtins.int, nanos: builtins.int, time_zone_offset: builtins.int) -> OffsetDatetime:
        r"""
        Create a `OffsetDatetime` from epoch seconds, nanoseconds, and time zone offset.
        
        Args:
            epoch_seconds (int): offset seconds from epoch (1970-01-01 00:00:00)
            nanos (int): nanosecond part of the time (0-999,999,999)
            time_zone_offset (int): time zone offset in minutes
        
        Returns:
            OffsetDatetime: created `OffsetDatetime` object
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class OffsetTime:
    r"""
    TIME WITH TIME ZONE type.
    
    Attributes:
        value (Optional[datetime.time]): time value with time zone. (read only)
        nanosecond (Optional[int]): nanosecond part of the time. (read only)
    """
    @property
    def value(self) -> typing.Optional[datetime.time]:
        r"""
        Value.
        """
    @property
    def nanosecond(self) -> typing.Optional[builtins.int]:
        r"""
        Nnanosecond.
        """
    def __new__(cls, value: typing.Optional[datetime.time] = None, nanosecond: typing.Optional[builtins.int] = None) -> OffsetTime:
        r"""
        Create a new `OffsetTime`.
        """
    @classmethod
    def of(cls, hour: builtins.int = 0, minute: builtins.int = 0, second: builtins.int = 0, nanosecond: builtins.int = 0, tzinfo: typing.Optional[datetime.tzinfo] = None) -> OffsetTime:
        r"""
        Create a `OffsetTime` from hour, minute, second, nanosecond, and tzinfo.
        
        Args:
            hour (int, optional): hour (0-23)
            minute (int, optional): minute (0-59)
            second (int, optional): second (0-59)
            nanosecond (int, optional): nanosecond (0-999,999,999)
            tzinfo (datetime.tzinfo, optional): time zone info (Default: UTC)
        
        Returns:
            OffsetTime: created `OffsetTime` object
        """
    @classmethod
    def raw(cls, nanoseconds_of_day: builtins.int, time_zone_offset: builtins.int) -> OffsetTime:
        r"""
        Create a `OffsetTime` from epoch nanoseconds of day and time zone offset.
        
        Args:
            nanoseconds_of_day (int): offset nano-seconds from epoch (00:00:00) in the time zone
            time_zone_offset (int): timezone offset in minute
        
        Returns:
            OffsetTime: created `OffsetTime` object
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ShutdownOption:
    r"""
    Shutdown option for connection.
    
    Attributes:
        shutdown_type (ShutdownType): Shutdown type. Default is `ShutdownType.GRACEFUL`.
        shutdown_timeout (int): Shutdown timeout in seconds.
    
    Examples:
        ```python
        import tsubakuro_rust_python as tsurugi
    
        shutdown_option = tsurugi.ShutdownOption(tsurugi.ShutdownType.GRACEFUL, 30)
        ```
    """
    @property
    def shutdown_type(self) -> tsubakurorustpython.ShutdownType:
        r"""
        Shutdown type.
        """
    @shutdown_type.setter
    def shutdown_type(self, value: tsubakurorustpython.ShutdownType) -> None:
        r"""
        Shutdown type.
        """
    @property
    def shutdown_timeout(self) -> typing.Optional[builtins.int]:
        r"""
        Shutdown timeout in seconds.
        """
    @shutdown_timeout.setter
    def shutdown_timeout(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Shutdown timeout in seconds.
        """
    def __new__(cls, shutdown_type: ShutdownType = ShutdownType.GRACEFUL, timeout: typing.Optional[builtins.int] = None) -> ShutdownOption:
        r"""
        Create a new `ShutdownOption`.
        """

@typing.final
class Str:
    r"""
    CHAR, VARCHAR type.
    
    Attributes:
        value (Optional[str]): string value. (read only)
    """
    @property
    def value(self) -> typing.Optional[builtins.str]:
        r"""
        Value.
        """
    def __new__(cls, value: typing.Optional[builtins.str] = None) -> Str:
        r"""
        Create a new `Str`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class TableMetadata:
    r"""
    Table metadata.
    
    Attributes:
        database_name (str): Database name. (read only)
        schema_name (str): Schema name. (read only)
        table_name (str): Table name. (read only)
        table_description (Optional[str]): Table description. (read only)
        columns (List[Column]): Columns metadata. (read only)
        description (Sequence[Tuple[str, str, None, Optional[int], Optional[int], Optional[int], Optional[bool]]]): Columns description.
          `(name, type_code, display_size, internal_size, precision, scale, null_ok)`. (read only)
        primary_keys (List[str]): Primary keys. (read only)
    """
    @property
    def database_name(self) -> builtins.str:
        r"""
        Database name.
        """
    @property
    def schema_name(self) -> builtins.str:
        r"""
        Schema name.
        """
    @property
    def table_name(self) -> builtins.str:
        r"""
        Table name.
        """
    @property
    def table_description(self) -> typing.Optional[builtins.str]:
        r"""
        Table description.
        """
    @property
    def columns(self) -> builtins.list[Column]:
        r"""
        Columns metadata.
        """
    @property
    def description(self) -> Sequence[Tuple[
        str,           # name
        str,           # type_code
        None,          # display_size
        Optional[int], # internal_size
        Optional[int], # precision
        Optional[int], # scale
        Optional[bool] # null_ok
    ]]:
        r"""
        Columns description.
        """
    @property
    def primary_keys(self) -> builtins.list[builtins.str]:
        r"""
        Primary keys.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Time:
    r"""
    TIME type.
    
    Attributes:
        value (Optional[datetime.time]): time value. (read only)
        nanosecond (Optional[int]): nanosecond part of the time. (read only)
    """
    @property
    def value(self) -> typing.Optional[datetime.time]:
        r"""
        Value.
        """
    @property
    def nanosecond(self) -> typing.Optional[builtins.int]:
        r"""
        Nnanosecond.
        """
    def __new__(cls, value: typing.Optional[datetime.time] = None, nanosecond: typing.Optional[builtins.int] = None) -> Time:
        r"""
        Create a new `Time`.
        """
    @classmethod
    def of(cls, hour: builtins.int = 0, minute: builtins.int = 0, second: builtins.int = 0, nanosecond: builtins.int = 0) -> Time:
        r"""
        Create a `Time` from hour, minute, second, and nanosecond.
        
        Args:
            hour (int, optional): hour (0-23)
            minute (int, optional): minute (0-59)
            second (int, optional): second (0-59)
            nanosecond (int, optional): nanosecond (0-999,999,999)
        
        Returns:
            Time: created `Time` object
        """
    @classmethod
    def raw(cls, nanoseconds_of_day: builtins.int) -> Time:
        r"""
        Create a `Time` from nanoseconds of day.
        
        Args:
            nanoseconds_of_day (int): time of day (nanoseconds since 00:00:00)
        
        Returns:
            Time: created `Time` object
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class TransactionOption:
    r"""
    Transaction option.
    
    Attributes:
        transaction_type (TransactionType): Transaction type. Default is `TransactionType.OCC`.
        label (str): Transaction label.
        include_ddl (bool): Whether the transaction modifies definitions (DDL). Default is `False`. Only applicable for `TransactionType.LTX`.
        write_preserve (List[str]): List of table names to preserve for write operations. Only applicable for `TransactionType.LTX`.
        inclusive_read_area (List[str]): List of table names to include in the read area. Only applicable for `TransactionType.LTX`.
        exclusive_read_area (List[str]): List of table names to exclude from the read area. Only applicable for `TransactionType.LTX`.
        scan_parallel (int): Degree of parallelism for scanning. Only applicable for `TransactionType.RTX`.
        begin_timeout (int): Begin transaction timeout in seconds
    
    Examples:
        ```python
        import tsubakuro_rust_python as tsurugi
    
        tx_option = tsurugi.TransactionOption(tsurugi.TransactionType.OCC)
        tx_option.label = "tsubakuro-rust-python OCC example"
        ```
    
        ```python
        import tsubakuro_rust_python as tsurugi
    
        tx_option = tsurugi.TransactionOption(tsurugi.TransactionType.LTX)
        tx_option.label = "tsubakuro-rust-python LTX example"
        tx_option.write_preserve = ["table1", "table2"]
        ```
    
        ```python
        import tsubakuro_rust_python as tsurugi
    
        tx_option = tsurugi.TransactionOption(tsurugi.TransactionType.RTX)
        tx_option.label = "tsubakuro-rust-python RTX example"
        tx_option.scan_parallel = 4
        ```
    """
    @property
    def transaction_type(self) -> tsubakurorustpython.TransactionType:
        r"""
        Transaction type.
        """
    @transaction_type.setter
    def transaction_type(self, value: tsubakurorustpython.TransactionType) -> None:
        r"""
        Transaction type.
        """
    @property
    def label(self) -> typing.Optional[builtins.str]:
        r"""
        Transaction label.
        """
    @label.setter
    def label(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Transaction label.
        """
    @property
    def include_ddl(self) -> builtins.bool:
        r"""
        Include DDL flag.
        """
    @include_ddl.setter
    def include_ddl(self, value: builtins.bool) -> None:
        r"""
        Include DDL flag.
        """
    @property
    def write_preserve(self) -> typing.Optional[builtins.list[builtins.str]]:
        r"""
        Write preserve.
        """
    @write_preserve.setter
    def write_preserve(self, value: typing.Optional[builtins.list[builtins.str]]) -> None:
        r"""
        Write preserve.
        """
    @property
    def inclusive_read_area(self) -> typing.Optional[builtins.list[builtins.str]]:
        r"""
        Inclusive read area.
        """
    @inclusive_read_area.setter
    def inclusive_read_area(self, value: typing.Optional[builtins.list[builtins.str]]) -> None:
        r"""
        Inclusive read area.
        """
    @property
    def exclusive_read_area(self) -> typing.Optional[builtins.list[builtins.str]]:
        r"""
        Exclusive read area.
        """
    @exclusive_read_area.setter
    def exclusive_read_area(self, value: typing.Optional[builtins.list[builtins.str]]) -> None:
        r"""
        Exclusive read area.
        """
    @property
    def scan_parallel(self) -> typing.Optional[builtins.int]:
        r"""
        Scan parallel.
        """
    @scan_parallel.setter
    def scan_parallel(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Scan parallel.
        """
    @property
    def begin_timeout(self) -> typing.Optional[builtins.int]:
        r"""
        Begin transaction timeout in seconds.
        """
    @begin_timeout.setter
    def begin_timeout(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Begin transaction timeout in seconds.
        """
    def __new__(cls, r#type: TransactionType = TransactionType.OCC) -> TransactionOption: ...

@typing.final
class CommitType(enum.Enum):
    r"""
    Commit type for transaction.
    
    Attributes:
        DEFAULT: the default commit type (rely on the database settings).
        ACCEPTED: commit operation has accepted, and the transaction will never abort except system errors.
        AVAILABLE: commit data has been visible for others.
        STORED: commit data has been saved on the local disk.
        PROPAGATED: commit data has been propagated to the all suitable nodes.
    """
    DEFAULT = ...
    r"""
    the default commit type (rely on the database settings).
    """
    ACCEPTED = ...
    r"""
    commit operation has accepted, and the transaction will never abort except system errors.
    """
    AVAILABLE = ...
    r"""
    commit data has been visible for others.
    """
    STORED = ...
    r"""
    commit data has been saved on the local disk.
    """
    PROPAGATED = ...
    r"""
    commit data has been propagated to the all suitable nodes.
    """

@typing.final
class ShutdownType(enum.Enum):
    r"""
    Shutdown type for connection.
    
    Attributes:
        NOTHING: Do nothing special during shutdown.
        GRACEFUL: Waits for the ongoing requests and safely shutdown the session.
        FORCEFUL: Cancelling the ongoing requests and safely shutdown the session.
    """
    NOTHING = ...
    r"""
    Do nothing special during shutdown.
    """
    GRACEFUL = ...
    r"""
    Waits for the ongoing requests and safely shutdown the session.
    """
    FORCEFUL = ...
    r"""
    Cancelling the ongoing requests and safely shutdown the session.
    """

@typing.final
class TransactionType(enum.Enum):
    r"""
    Transaction type.
    
    Attributes:
        OCC: Optimistic concurrency control (OCC) transaction.
        LTX: Long transaction (LTX).
        RTX: Read-only transaction (RTX).
    """
    OCC = ...
    r"""
    Optimistic concurrency control (OCC) transaction.
    """
    LTX = ...
    r"""
    Long transaction (LTX).
    """
    RTX = ...
    r"""
    Read-only transaction (RTX).
    """

@typing.overload
def connect(*args: typing.Any, **kwargs: typing.Any) -> tsubakurorustpython.Connection:
    r"""
    Constructor for creating a connection to the Tsurugi.
    
    Args:
        *args (Config, optional): configuration object.
        **kwargs (dict, optional): e.g. `endpoint="tcp://localhost:12345"`, `user="tsurugi"`
    
    Returns:
        Connection: Connection object.
    
    Examples:
        ```python
        import tsubakuro_rust_python as tsurugi
    
        config = tsurugi.Config()
        config.endpoint = "tcp://localhost:12345"
        config.user = "tsurugi"
        config.password = "password"
        config.default_timeout = 30 // seconds
        with tsurugi.connect(config) as connection:
            pass
        ```
    
        ```python
        import tsubakuro_rust_python as tsurugi
    
        with tsurugi.connect(endpoint="tcp://localhost:12345", user="tsurugi", password="password", default_timeout=30) as connection:
            pass
        ```
    """

@typing.overload
def connect(*args: tsubakuro_rust_python.Config) -> tsubakuro_rust_python.Connection: ...

@typing.overload
def connect(*args: Any) -> tsubakuro_rust_python.Connection: ...

@typing.overload
def connect(**kwargs: Any) -> tsubakuro_rust_python.Connection: ...

def env_logger_init(filters: builtins.str = 'tsubakuro_rust_python=info', file_path: typing.Optional[builtins.str] = None) -> None:
    r"""
    Initialize env_logger.
    
    Args:
        filters (str, optional): filter string. If ommitted, `"tsubakuro_rust_python=info"` is used.
        file_path (str, optional): log file path. If None, logs to stderr.
    
    Examples:
        ```python
        import tsubakuro_rust_python as tsurugi
    
        tsurugi.env_logger_init("tsubakuro_rust_python=trace")
        ```
    
    Note:
        Calls to `env_logger_init` other than the first one are ignored.
    """

