name: Tsubakuro-Rust-CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      tsurugi_version:
        type: string
        default: 'snapshot'
      os:
        type: string
        default: 'ubuntu-22.04'
      tsurugi_loglevel:
        type: number
        default: 30
      jobs_to_run:
        type: choice
        options:
          - Build
          - Build_Python
          - Build_Wheel
          - Publish_PyPI
          - Build_Windows
          - All
        default: All

jobs:
  Build:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.jobs_to_run == 'Build' || inputs.jobs_to_run == 'All' }}
    runs-on: ${{ inputs.os || 'ubuntu-22.04' }}
    permissions:
      checks: write
      contents: write
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    env:
      DBTEST_ENDPOINT      : tcp://localhost:12345
      DBTEST_ENDPOINT_JAVA : tcp://localhost:12345
      GLOG_v               : ${{ inputs.tsurugi_loglevel || 30 }}

    services:
      tsurugi:
        image: ghcr.io/project-tsurugi/tsurugidb:${{ inputs.tsurugi_version || 'snapshot' }}-${{ inputs.os || 'ubuntu-22.04' }}
        ports:
          - 12345:12345
        env:
          GLOG_v: ${{ inputs.tsurugi_loglevel || 30 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Apt_Install
        run: |
          if command -v apt-get > /dev/null; then
            sudo apt-get update -y
            sudo apt-get install -y protobuf-compiler
          fi

      - name: Test_Core
        run: |
          cd tsubakuro-rust-core
          cargo build
          cargo test

      - name: Test_DBTest
        run: |
          cd tsubakuro-rust-dbtest
          cargo run ${DBTEST_ENDPOINT} tsurugi password
          cargo test "" -- --test-threads=1 endpoint=${DBTEST_ENDPOINT}

      - name: Build_FFI
        run: |
          cd tsubakuro-rust-ffi
          cargo build --release

      - name: Test_Java
        run: |
          cd tsubakuro-rust-java
          ./gradlew test -Pffi.library.path=${GITHUB_WORKSPACE}/tsubakuro-rust-ffi/target/release/libtsubakuro_rust_ffi.so -Pdbtest.endpoint=${DBTEST_ENDPOINT} -Pdbtest.endpoint.java=${DBTEST_ENDPOINT_JAVA}

      - name: Lint_Core
        run: |
          cd tsubakuro-rust-core
          cargo clippy

      - name: Lint_FFI
        run: |
          cd tsubakuro-rust-ffi
          cargo clippy

      - name: Publish_Core
        if: github.repository_owner == 'project-tsurugi' && startsWith(github.ref, 'refs/tags/')
        run: |
          cd tsubakuro-rust-core
          cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO }}

      - name: Create_GitHub_Release
        if: github.repository_owner == 'project-tsurugi' && startsWith(github.ref, 'refs/tags/')
        run: |
          gh release create ${TSUBAKURO_RUST_VERSION} --title ${TSUBAKURO_RUST_VERSION} --latest --repo project-tsurugi/tsubakuro-rust
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TSUBAKURO_RUST_VERSION: ${{ github.ref_name }}

  Build_Python:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.jobs_to_run == 'Build_Python' || inputs.jobs_to_run == 'All' }}
    runs-on: ${{ inputs.os || 'ubuntu-22.04' }}
    permissions:
      checks: write
      contents: read
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    env:
      DBTEST_ENDPOINT      : tcp://localhost:12345
      GLOG_v               : ${{ inputs.tsurugi_loglevel || 30 }}

    services:
      tsurugi:
        image: ghcr.io/project-tsurugi/tsurugidb:${{ inputs.tsurugi_version || 'snapshot' }}-${{ inputs.os || 'ubuntu-22.04' }}
        ports:
          - 12345:12345
        env:
          GLOG_v: ${{ inputs.tsurugi_loglevel || 30 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Apt_Install
        run: |
          if command -v apt-get > /dev/null; then
            sudo apt-get update -y
            sudo apt-get install -y protobuf-compiler
          fi

      - name: Install_uv
        uses: astral-sh/setup-uv@v7

      - name: Test_Python
        run: |
          cd tsubakuro-rust-python
          uv run pytest

      - name: Test_Python_DBTest_With_Minimum_Python_Version
        run: |
          cd tsubakuro-rust-python-dbtest
          uv run --python 3.10 pytest --endpoint=${DBTEST_ENDPOINT}

      - name: Test_Python_DBTest_With_Latest_Python_Version
        run: |
          cd tsubakuro-rust-python-dbtest
          uv run --python 3.14 pytest --endpoint=${DBTEST_ENDPOINT}

      - name: Lint_Python
        run: |
          cd tsubakuro-rust-python
          cargo clippy

  Build_Wheel_linux:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.jobs_to_run == 'Build_Wheel' || inputs.jobs_to_run == 'Publish_PyPI' || inputs.jobs_to_run == 'All' }}
    runs-on: ${{ matrix.platform.runner }}
    permissions:
      contents: read
    strategy:
      matrix:
        platform:
          - runner: ubuntu-22.04
            target: x86_64
          # - runner: ubuntu-22.04
          #   target: x86
          # - runner: ubuntu-22.04
          #   target: aarch64
          # - runner: ubuntu-22.04
          #   target: armv7
          # - runner: ubuntu-22.04
          #   target: s390x
          # - runner: ubuntu-22.04
          #   target: ppc64le
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --compatibility pypi
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          manylinux: 2_28
          working-directory: tsubakuro-rust-python
          before-script-linux: |
            dnf install -y protobuf-devel

      # - name: Build free-threaded wheels
      #   uses: PyO3/maturin-action@v1
      #   with:
      #     target: ${{ matrix.platform.target }}
      #     args: --release --out dist -i python3.14t --compatibility pypi
      #     sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
      #     manylinux: auto
      #     working-directory: tsubakuro-rust-python

      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheels-tsurugi-dbapi-linux-${{ matrix.platform.target }}
          path: tsubakuro-rust-python/dist

  Build_Wheel_musllinux:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.jobs_to_run == 'Build_Wheel' || inputs.jobs_to_run == 'Publish_PyPI' || inputs.jobs_to_run == 'All' }}
    runs-on: ${{ matrix.platform.runner }}
    permissions:
      contents: read
    strategy:
      matrix:
        platform:
          - runner: ubuntu-22.04
            target: x86_64
          # - runner: ubuntu-22.04
          #   target: x86
          # - runner: ubuntu-22.04
          #   target: aarch64
          # - runner: ubuntu-22.04
          #   target: armv7
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --compatibility pypi
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          manylinux: musllinux_1_2
          working-directory: tsubakuro-rust-python
          before-script-linux: |
            sudo apt-get update -y
            sudo apt-get install -y protobuf-compiler

      # - name: Build free-threaded wheels
      #   uses: PyO3/maturin-action@v1
      #   with:
      #     target: ${{ matrix.platform.target }}
      #     args: --release --out dist -i python3.14t --compatibility pypi
      #     sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
      #     manylinux: musllinux_1_2
      #     working-directory: tsubakuro-rust-python

      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheels-tsurugi-dbapi-musllinux-${{ matrix.platform.target }}
          path: tsubakuro-rust-python/dist

  Build_Wheel_windows:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.jobs_to_run == 'Build_Wheel' || inputs.jobs_to_run == 'Publish_PyPI' || inputs.jobs_to_run == 'All' }}
    runs-on: ${{ matrix.platform.runner }}
    permissions:
      contents: read
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x64
            python_arch: x64
          # - runner: windows-latest
          #   target: x86
          #   python_arch: x86
          # - runner: windows-11-arm
          #   target: aarch64
          #   python_arch: arm64
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
          architecture: ${{ matrix.platform.python_arch }}

      - name: Install_Protobuf
        run: |
          choco install protoc -y

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --compatibility pypi
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          working-directory: tsubakuro-rust-python

      # - uses: actions/setup-python@v6
      #   with:
      #     python-version: 3.14t
      #     architecture: ${{ matrix.platform.python_arch }}

      # - name: Build free-threaded wheels
      #   uses: PyO3/maturin-action@v1
      #   with:
      #     target: ${{ matrix.platform.target }}
      #     args: --release --out dist -i python3.14t --compatibility pypi
      #     sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
      #     working-directory: tsubakuro-rust-python

      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheels-tsurugi-dbapi-windows-${{ matrix.platform.target }}
          path: tsubakuro-rust-python/dist

  Build_Wheel_macos:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.jobs_to_run == 'Build_Wheel' || inputs.jobs_to_run == 'Publish_PyPI' || inputs.jobs_to_run == 'All' }}
    runs-on: ${{ matrix.platform.runner }}
    permissions:
      contents: read
    strategy:
      matrix:
        platform:
          # - runner: macos-15-intel
          #   target: x86_64
          - runner: macos-latest
            target: aarch64
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Install Protoc
        run: |
          brew install protobuf

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --compatibility pypi
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          working-directory: tsubakuro-rust-python

      # - name: Build free-threaded wheels
      #   uses: PyO3/maturin-action@v1
      #   with:
      #     target: ${{ matrix.platform.target }}
      #     args: --release --out dist -i python3.14t --compatibility pypi
      #     sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
      #     working-directory: tsubakuro-rust-python

      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheels-tsurugi-dbapi-macos-${{ matrix.platform.target }}
          path: tsubakuro-rust-python/dist

  Build_Wheel_sdist:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.jobs_to_run == 'Build_Wheel' || inputs.jobs_to_run == 'Publish_PyPI' || inputs.jobs_to_run == 'All' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist
          working-directory: tsubakuro-rust-python

      - name: Upload sdist
        uses: actions/upload-artifact@v6
        with:
          name: wheels-tsurugi-dbapi-sdist
          path: tsubakuro-rust-python/dist

  Publish_PyPI:
    if: ${{ github.repository_owner == 'project-tsurugi' && (startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && (inputs.jobs_to_run == 'Publish_PyPI' || inputs.jobs_to_run == 'All'))) }}
    runs-on: ubuntu-latest
    needs: [Build_Wheel_linux, Build_Wheel_musllinux, Build_Wheel_windows, Build_Wheel_macos, Build_Wheel_sdist]
    permissions:
      # Use to sign the release artifacts
      id-token: write
      # Used to upload release artifacts
      contents: write
      # Used to generate artifact attestation
      attestations: write
    steps:
      - uses: actions/download-artifact@v7

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: 'wheels-*/*'

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Publish to PyPI
        run: uv publish 'wheels-*/*'
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

  Build_Windows:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.jobs_to_run == 'Build_Windows' || inputs.jobs_to_run == 'All' }}
    runs-on: windows-2022
    permissions:
      checks: write
      contents: write
    timeout-minutes: 30
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install_Protobuf
        run: |
          choco install protoc -y

      - name: Test_Core
        run: |
          cd tsubakuro-rust-core
          cargo build
          cargo test

      - name: Test_ODBC
        run: |
          cd tsubakuro-rust-odbc
          cargo build --release
          ls -l target/release/

          cargo test

      - name: Build_Installer
        run: |
          cd tsubakuro-rust-odbc/installer
          ISCC.exe installer.iss

          ls -l Output/

      - name: Lint_ODBC
        continue-on-error: true
        run: |
          cd tsubakuro-rust-odbc
          cargo clippy

      - name: Upload_DLL
        uses: actions/upload-artifact@v4
        with:
          name: tsubakuro_rust_odbc.dll
          path: tsubakuro-rust-odbc/target/release/tsubakuro_rust_odbc.dll

      - name: Upload_Installer
        uses: actions/upload-artifact@v4
        with:
          name: tsurugi_odbc_driver_installer.exe
          path: tsubakuro-rust-odbc/installer/Output/tsurugi_odbc_driver_installer.exe
